- .gitmodules
This fixes problem with git modules
> Fix git submodule repositories

- .gitignore
- bin/dev/install_tools.sh
- make/run
See also https://github.com/SUSE/uaa-fissile-release/pull/20
> Use secrets as such.

- container-host-files/etc/hcf/config/role-manifest.yml
Both roles need to wait for UAA to be ready before continuing; otherwise they get stuck (cached broken token?).
> Fix routing-api/router startup

- bin/dev/versions.sh
Verbose options added for `fissile show ...`
> Update fissile version

- README.md
This is a followup to the recently merged PR #974.
> Updated README for new make targets (smoke, cats)

- make/include/versioning
This is more widely supported.
> Use $0 instead of BASH_SOURCE

- bin/dev/install_tools.sh
If we are not on vagrant, don't randomly try to install tiller on a kubernetes.  We might not have one available (e.g. CI), or we might be pointing at a different one (e.g. developer workstation).
> vagrant: don't install helm-tiller outside vagrant

- Makefile
- README.md
- bin/generate-dev-certs.sh
- docker-images/cert-generator/Dockerfile
- docker-images/cert-generator/cert-generator.sh
- docker-images/cert-generator/scf-cert-generator.sh
- make/cert-generator
Add a cert generator container with our support scripts so customers can generate their own certs.
> Isolated cert generator

- bin/dev/versions.sh
- bin/generate-dev-certs.sh
- container-host-files/etc/hcf/config/role-manifest.yml
- container-host-files/etc/hcf/config/scripts/configure-HA-hosts.sh
> kube: replace -pod with -set

- .envrc
- README.md
- bin/dev/versions.sh
- container-host-files/etc/hcf/config/scripts/chown_vcap_store.sh
- src/hcf-release/jobs/uaa-create-user/templates/run.erb
This PR fixes compatibility issues to run ubuntu atop scf.
> Fix ubuntu for scf

- make/cats
- make/smoke
This timed out for me a few times. Would be nice to get a more accurate timing as well.
> Poll for smoke+cats instead of hardcoded sleep

- container-host-files/etc/hcf/config/role-manifest.yml
How can/should this be tested ?
> Move key length from cert parameter to corresponding key.

- README.md
> Add default creds to docs.

- bin/dev/k8s-ready-state-check.sh
The original code is found in the `cf-ci` repository.
A separate ticket will excise it from there, and update the pipeline.
This is the new official location.
Until `cf-ci` is updated changes to the script here must be sync'd over.
> This is the `I am OK` script to check that a k8s cluster properly supports SCF.

- make/cert-generator
Rebased
Associated CI PR is https://github.com/SUSE/cf-ci/pull/20
> Modified cert-generator to prefer local certstrap archives over downloading

- .gitignore
- make/kube-dist
This makes `make kube-dist` generate both kube and helm bits
> Generate separate kube and helm artifacts

- Vagrantfile
> vagrant: bump libvirt box version to 2.0.5

- bin/dev/versions.sh
This pulls in changes to make the image tags more predicable.
> Bump fissile version

- bin/dev/vagrant-envrc
Rather than waiting for Andreas' to come back, I've merged his branch, and added some cleanup here.
> Cleanup vagrant envrc

- make/bundle-dist
- make/include/versioning
Also move things around a bit in the file name
> versioning: fix handling tags with dashes

- Jenkinsfile
Saves output into four different dirs:
* ./ (master)
* ./prs/
* ./branches/
* ./develop/
> Split output of Jenkins builds

- bin/common/versions.sh
- make/kube
Note that the uaa-fissile-release subdir should point to master before merging SCF.
> Provide helm chart

- Jenkinsfile
- packer/scripts/compact.sh
I recommend adding `?w=1` to the GitHub URL (or use `git diff -w`), since the whitespace change is insignificant.
> Clean up Jenkinsfile

- NOTES.txt
- make/kube
https://trello.com/c/rLlRrQRo/342-1-create-a-notestxt-as-part-of-the-helm-packages
> Deploy a templated NOTES.txt file upon start.

- packer/vagrant-box.json
to be able to push files to OBS.
> Add OSC to Jenkins workers

- Jenkinsfile
- Also make jenkins file the same in both branches
> Add master folder for jenkins

- Jenkinsfile
- Makefile
- bin/dev/legalscan.sh
- make/osc-commit-sources
- make/tar-sources
This PR adds functionality for publishing the source codes used to build scf on obs
> Commit source tars

- bin/common/versions.sh
@aarondl wrote: "@jandubois Feel free to update helm."
https://chat.microfocus.net/channel/suse-paas?msg=HeaZdhcGC3YJBwbfx
So here it is. 😄 
Tested on latest Vagrant box.
> Update to latest helm 2.6.2

- .gitignore
- Makefile
- make/registry
- make/secure-registries
```
make secure-registries
REGISTRY_USERNAME=admin REGISTRY_PASSWORD=changeme make registry
docker login -u admin -p changeme registry.cf-dev.io:5000
```
> Add support for secure registry inside the Vagrant box

- container-host-files/etc/hcf/config/role-manifest.yml
This is based on the self-anti-affinity PR #1133, and shouldn't be merged until that previous PR is merged.
> Add router + diego-cell anti-affinity

- src/hcf-release/jobs/acceptance-tests-brain/templates/pre-start.erb
- src/hcf-release/src/acceptance-tests-brain/test-resources/resources.csv
- src/hcf-release/src/acceptance-tests-brain/test-scripts/008_cf_usb_test.sh
https://trello.com/c/vWwV1UJE/426-add-cf-usb-brain-tests-back
pre-start: install the cf-usb plugin for the cf cli
new test file. details of the test in the comment of that file.
> Resurrect the cf-usb test.

- Jenkinsfile
- This allows disabling a slave for scheduling, and ssh'ing on to it so
we can look at what happened to a build.
> Stop clean up after builds

- Jenkinsfile
- We need to investigate why this is occurring. This will be temporary.
> Jenkins tests are failing pathologically

- .gitmodules
- bin/common/versions.sh
- bin/dev/install_tools.sh
- container-host-files/etc/hcf/config/role-manifest.yml
- src/hcf-release/jobs/generate-secrets/spec
- src/hcf-release/jobs/generate-secrets/templates/run.erb
- src/hcf-release/packages/acceptance-tests-brain/packaging
- src/hcf-release/packages/acceptance-tests-brain/spec
- src/hcf-release/packages/generate-secrets/packaging
- src/hcf-release/packages/generate-secrets/spec
First pass at doing secret generation through a job. 
https://github.com/SUSE/fissile/pull/300 should be merged first, and then I can update this PR for the fissile master build.
Also needing merges:
* https://github.com/SUSE/uaa-fissile-release/pull/58
* https://github.com/SUSE/scf-secret-generator/pull/1
> Move secret generation to job

- Makefile
- make/uaa-compile
Ref: https://trello.com/c/kLg2Mf6P/477-2-uaa-fissile-release-split-make-images-up-so-it-doesnt-call-make-releases-compile-images
- Moved the uaa-* targets into their own section
- Inserted new uaa linkage into releases and compile targets.
- Fixed make target in uaa-images linkage script
- Sub module change (https://github.com/SUSE/uaa-fissile-release/pull/62)
> Match the changes in the uaa-fissile-release, plus tweaks

- bin/cert-generator-wrapper.sh.in
- bin/settings/kube/ca.sh
- container-host-files/etc/hcf/config/role-manifest.yml
- make/run
- src/hcf-release/jobs/authorize_internal_ca/templates/pre-start.erb
Ref: https://trello.com/c/Qta9UaxM/98-1-rename-uaas-hcpcacert-to-uaacacert
> Rename uaa's hcp_ca_cert to uaa_ca_cert

- bin/create-release.sh
Deleting the entire dev_builds dir causes the bosh-cache files to
be orphaned.
This includes a fix to the UAA bin/create-release.sh script.
~~~*NOTE* This needs https://github.com/SUSE/uaa-fissile-release/pull/63 to be merged to master first, so the submodule pointer can be updated.~~~
> Delete index files if cache files are missing

- container-host-files/etc/hcf/config/role-manifest.yml
Resolves https://github.com/SUSE/scf/issues/1211
> diego-api isn't a StatefulSet

- container-host-files/etc/hcf/config/opinions.yml
The dark fire will not avail you, flame of Udûn!
Go back to the Shadow!
> Remove opinion for unused IIS buildpack

- NOTES.txt
Just a TYPO fix in `NOTES.txt` I saw.
> TYPO fix in NOTES.txt

- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
- src/scf-helper-release/jobs/uaa-create-user/templates/run.erb
The upstream Ubuntu stemcell doesn't have `jq`, use python as it's available by default on all stemcells.
> Remove jq requirement

- container-host-files/etc/scf/config/role-manifest.yml
This makes it clearer which certificate names are actually required.
Blocked on https://github.com/SUSE/scf-secret-generator/pull/9 (and will need to update the submodule commit afterwards).
> Remove unnecessary certificate subject names in role manifest

- .envrc
- Jenkinsfile
- bin/common/versions.sh
- make/run
Do not merge until the dependencies are merged:
> Make rbac the default

- bin/config-validator.rb
- bin/vagrant-setup/common.rb
- bin/validation.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/forward_logfiles.sh
Please see [bsc#1075602](https://bugzilla.suse.com/show_bug.cgi?id=1075602) for details; this basically unbreaks syslog forwarding
> Various syslog fixes from bsc#1075602

- container-host-files/etc/scf/config/opinions.yml
> Pick up missing commit from Vlad's unfork CATS branch

- bin/common/versions.sh
- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
This PR must be reviewed *after* https://github.com/SUSE/scf/pull/1315 because it includes the `uaa-fissile-release` changes from that PR and adds another merge on top of it.
> Allow renaming of immutable secrets

- make/uaa-run
This allows UAA to have a configurable logging level.
> UAA: Bump for logging changes

- Jenkinsfile
- bin/common/versions.sh
- make/run
- make/stop
This updates SCF itself to use multiple IPs (one of which is not real and is just there to test the change).
> Allow more than one IP address for external IPs

- packer/.gitignore
- packer/scripts/install-cap-archives.sh
Bump to scf 2.7.0 and console 1.0.0.
> Update cached vagrant box

- bin/dev/create_helm_charts_pr.sh
The pr should look like this:
title: `scf-sle-2.7.0 and cf1.9.0.0.g2d95fcb5.darwin-amd64`
description: `Created by https://jenkins-new.howdoi.website/job/scf-master-sles/49/`
> Create human readable prs for helm charts

- src/scf-helper-release/packages/acceptance-tests-brain/packaging
- src/scf-helper-release/src/acceptance-tests-brain/test-resources/resources.csv
- src/scf-helper-release/src/acceptance-tests-brain/test-scripts/009_backup_test.sh
This just restores the old tests we removed
> Add backup tests

- container-host-files/etc/scf/config/role-manifest.yml
https://trello.com/c/LMQ39o4b/597-2-make-sure-certificates-are-not-immutable
> Drop immutability of the UAA_CA_CERT. No other cert is immutable.

- bin/kube_overrides.rb
- make/tests
This code is derived from the Jenkinsfile and can hopefully
shared with it in the future.
[trello#42gyM3NL]
> Update make/tests for new secrets generator mechanics

- Jenkinsfile
> Switch Jenkinsfile to use bin/kube_overrides.rb

- bin/common/versions.sh
Ref https://trello.com/c/8RKI6NUG/604-transmogrify-undefined-method-zero
> Bump fissile to get index calculation changes.

- bin/dev/legalscan.sh
Signed-off-by: Christian Richter <crichter@suse.com>
> Add sidecars to legalscan.sh

- container-host-files/etc/scf/config/role-manifest.yml
All roles should have anti affinity with themselves.
> Add anti affinity to new syslog roles

- make/uaa-images
> Tell make/uaa-images about DOCKER_APP_VERSION

- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
it's try to fix the issue https://github.com/SUSE/scf/issues/1492
> fix scripts to support both k8s v1.8 and v1.9

- bin/common/versions.sh
Ref: https://trello.com/c/7xGqgWkI/671-3-make-sizing-section-of-valuesyaml-uniform
> Bump fissile version.

- Jenkinsfile
Add a dummy `--set` to helm upgrade to trigger the rotation.
> Add a step to Jenkins to trigger secret rotation

- bin/common/versions.sh
- bin/dev/install_tools.sh
The active/passive role branch in fissile has been merged now.
> Restore fissile version to master branch

- Jenkinsfile
- bin/clean-jenkins-log
Ref: https://trello.com/c/CSmv90Cr/696-3-jenkins-database-of-logs-to-track-failures
> Save logs of failed builds for post-mortem analysis

- Jenkinsfile
- container-host-files/etc/scf/config/role-manifest.yml
We now scale it up to non-zero before running the scaler tests
> autoscaler: Default to off

- container-host-files/etc/scf/config/opinions.yml
> Bump garden release

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
This is the subset of commits that should be compatible with HA deployment.
The remaining changes will have to wait for some fissile improvements.
> Realigning our role composition back with cf upstream part1

- bin/common/versions.sh
- bin/config-validator.rb
- container-host-files/etc/scf/config/role-manifest.yml
Top level `roles` -> `instance_groups`
Job's `release_name` -> `release`
> Rename role-manifest keys to match fissile 6+

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
This is a dummy PR to force a Jenkins run for #1658 — our CI doesn't trust forks.  I'll eventually close this and merge the other PR instead.
> Dummy PR to trigger Jenkins

- CHANGELOG.md
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
We need additional support to migrate data from previous installation during upgrade if we want to change the names of volume claims.
[trello#aOhLhzFF]
> Rename database role back to mysql

- make/compile
> Logic for skipping cache was inverted

- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/acceptance-tests/spec
This can be useful to reproduce issues
> CATS: allow customizing node count

- bin/common/versions.sh
> Bump stemcells for new configgin

- README.md
- bin/config-validator.rb
- container-host-files/etc/scf/config/role-manifest.yml
This pull request adapts the role manifest and the according validation code to the latest format changes in fissile.
**Note**: This requires changes in fissile which are in the `develop` branch, but `develop` also includes commits which require additional changes regarding the one-service-per-job change. This PR should thus currently **NOT** be merged until this is resolved.
**Note 2**: There's another pull request regarding this format change for [uaa-fissile-release](https://github.com/SUSE/uaa-fissile-release/pull/121). The submodule in `scf` or in this PR should be bumped once this is merged.
> Translate to new format

- bin/common/versions.sh
- bin/kube_overrides.rb
Ref:  https://trello.com/c/0U5Zs5Yw/791-2130-do-we-care-that-cats-sometimes-fails-on-asg-tests
SCF change for Fissile PR https://github.com/cloudfoundry-incubator/fissile/pull/402
>  Move writing of service accounts and roles bound to a single instance group from separate files to the file for the instance group.

- Jenkinsfile
The kube config files can now contain multiple kube object definitions, so are no longer usable via `kubectl run ... --overrides=...`. So instead of duplicating the logic from `make/tests`, let's just call it.
> Use make/tests from Jenkinsfile instead of custom logic

- bin/common/versions.sh
Ref: https://trello.com/c/KzfK2xOh/822-13-rc-deploy-issue-with-psp-cluster-roles
> Bump fissile for namespaced clusterrole(bindings).

- bin/kube_overrides.rb
> Update Cluster role names with namespace

- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/DVNMaxd0/735-5-evaluate-sizing-tests-and-update-docs-helm-charts-for-13
> [#DVNMaxd0] Update role sizing information from the Azure testing.

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
- src/scf-release/src/acceptance-tests-brain/test-resources/nfs_server_kube.yaml
> Use app.kubernetes.io/component instead of skiff-role-name label.

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Also simplify some other service names that use the same role and job names.
[trello#JmwDHOUp]
> Keep diego.file_server_url unchanged from previous release

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Dummy PR to make Jenkins build the original PR
Jenkins doesn't trust people who don't have push permissions.
> bump up app-autoscaler-release to final release 1.0.0

- bin/kube_overrides.rb
This is a cherry pick from `marky/minibroker-redis-brain` (PR #1774).
This makes the brain tests work again on vagrant.
Without this change the pod does not even start due to PSP issues.
> bin/kubeoverrides: override the namespace

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
For pretty much the same reason as #1800
> instance groups: make `api` be the ccng service for backwards compat

- bin/common/versions.sh
> Bump fissile to add nodeAffinity template to roles without podAntiAffinity

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-az.sh
- src/scf-release/jobs/get-kubectl/spec
Ref: https://trello.com/c/UXZXgy8V/843-patch-diego-cells-so-they-respond-to-az
- Script `configure-az.sh`
- Parameter `env.AZ_LABEL_NAME`
Trello has documentation attached, both how it works and how it was tested.
> Patch diego cells so they respond to AZ

- bin/common/versions.sh
- bin/dev/install_tools.sh
> Update to latest configgin and fissile

- .gitmodules
- Jenkinsfile
- bin/settings.yaml
- container-host-files/etc/scf/config/role-manifest.yml
- make/tests
- src/scf-release/jobs/acceptance-tests-brain/spec
- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
- src/scf-release/packages/helm/packaging
- src/scf-release/packages/helm/spec
- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.sh
This also, as a prerequisite:
- adds the helm binary to acceptance-tests-brain
- marks the brain pod as privileged (to be able to use helm)
> acceptance-tests-brain: add test for minibroker (redis)

- container-host-files/etc/scf/config/scripts/patches/cc_clock_disable_credhub.sh
- container-host-files/etc/scf/config/scripts/patches/cc_ng_disable_credhub.sh
- container-host-files/etc/scf/config/scripts/patches/cc_worker_disable_credhub.sh
Ref
* https://trello.com/c/Iw7NiIVy/876-3-dont-fork-credhub
* #1904
> Followup PR to PR 1904. Comment on the transient nature of the patch.

- container-host-files/etc/scf/config/role-manifest.yml
This reverts commit daa418614d486032062387128f6ef86344294954.
> Revert "Bump php-buildpack release to 4.3.67.1"

- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/role-manifest.yml
https://docs.cloudfoundry.org/buildpacks/nginx/
> Add nginx buildpack

- container-host-files/etc/scf/config/role-manifest.yml
Signed-off-by: Christian Richter <crichter@suse.com>
> Update dotnet-core buildpack in role-manifest

- bin/common/versions.sh
- bin/kube_overrides.rb
- container-host-files/etc/scf/config/role-manifest.yml
- make/run
- make/tests
- make/upgrade
This uses the changes from https://github.com/cloudfoundry-incubator/fissile/pull/460 to explicitly describe the PSPs we need, and the node-reader cluster role we need for diego-cell.  With this, we should not need to manually set up cluster roles & bindings.
> Set up default PSPs

- container-host-files/etc/scf/config/role-manifest.yml
References official final release of the modified groot-btrfs component.
Ref: https://trello.com/c/gkY3QsvZ/920-btrfs-pre-startup-script-kicks-in-even-when-gardenrootfsdriver-is-set-to-overlayxfs#
> btrfs setup fixes

- container-host-files/etc/scf/config/role-manifest.yml
Reverting bump of dontnet buildpack
Signed-off-by: Christian Richter <crichter@suse.com>
> Revert commit of dotnet-bump

- Makefile
- make/include/defaults
- make/stratos/metrics/run
- make/stratos/metrics/stop
- Run `make stratos-run`.
- Add Metrics to Stratos using the endpoint `https://cf-dev.io:8444`.
- Connect to it using the default username: metrics and password: s3cr3t.
> Added run and stop scripts for Stratos Metrics

- container-host-files/etc/scf/config/opinions-opensuse42.yml
- container-host-files/etc/scf/config/opinions-sle12.yml
- container-host-files/etc/scf/config/role-manifest.yml
> Add cflinuxfs3 stack to scf.

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-pz.sh
:warning: Spike
Ref: https://trello.com/c/zZmx9YQg/915-5-support-placement-zones-isolation-segments
Implementation analog to KUBE_AZ, AZ_LABEL_NAME, ...
Isolation segments can be specified on a per (worker-)node basis.
:construction: WIP. Do not merge. :construction:
> Spike: Isolation Segments.

- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/mapfs_pre_start.sh
- container-host-files/etc/scf/config/scripts/patches/nfs-volume-nfsv3driver-libdir.sh
- container-host-files/etc/scf/config/scripts/patches/nfsbroker_cert_prop.sh
- container-host-files/etc/scf/config/scripts/patches/nfsbroker_ctl.sh
- src/scf-release/jobs/configure-scf/templates/run.erb
- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
Ref https://trello.com/c/dOiHIcaP/847-5-update-nfs-volume-release-from-120-to-152-or-later
Blocked on CF bump. See last commit and its message, or the referenced ticket.
> Bump nfs-volume-release

- CHANGELOG.md
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_garden_logdir.sh
- tooling/bin/diff-releases.rb
- tooling/bin/import-bosh-releases
- tooling/lib/releases_diff.rb
This PR covers the exactly same commits as https://github.com/SUSE/scf/pull/2143
However it is not in draft status.
All discussion applies, as do the CI results.
> CF Bump 6.2.0

- CHANGELOG.md
- bin/common/versions.sh
- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/opinions-opensuse42.yml
- container-host-files/etc/scf/config/opinions-sle12.yml
- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/jKAvgx6W/929-5-post-131-cf-big-bump-part-2-as-most-recent-as-possible
UAA PR https://github.com/SUSE/uaa-fissile-release/pull/148
:white_check_mark: jenkins, vagrant
> CF Bump to 6.3.0

- Vagrantfile
- Removed trailing `m` from message.
- Removed unnecessary `Done ...` line.
> Updates to Vagrantfile customization scripts

- Jenkinsfile
Jenkinsfile doesn't interpolate single quotes.
> Fix Jenkinsfile quoting interpolation

- .envrc
- Jenkinsfile
- README.md
- bin/common/versions.sh
- bin/dev/create_helm_charts_pr.sh
- bin/fissile
- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/opinions-opensuse42.yml
- container-host-files/etc/scf/config/opinions-sle12.yml
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/mapfs_pre_start.sh
- make/bundle-dist
- make/kube
- make/kube-dist
- make/tar-sources
- make/tests
- tooling/lib/releases_diff.rb
Reverts SUSE/scf#2185
The private stemcell image broke develop. Let's figure out in another PR.
> Revert "Remove openSUSE and reduce everything to one build"

- container-host-files/etc/scf/config/role-manifest.yml
CC ports shouldn't be configurable by the user.
All tests should pass.
> Hardcode CC ports

- Jenkinsfile
Handling case when the prefix is returned empty
> Fixed issue in klog dump from Jenkins

- Jenkinsfile
Jenkins need the right registry and credentials while using SLE 12 stemcell.
Jenkins build should pass.
> Switched to staging registry and credentials as default on Jenkinsfile

- src/scf-release/src/acceptance-tests-brain/test-scripts/017_syslog_forwarding_test.rb
It looks like sometimes we end up trying to get logs from the syslog container while it's still in `ContainerCreating`, somehow (even though all conditions are ready); this probably happens because there is no conditions yet.
Explicitly check the container phase to work around this.
Also make it more obivous (in the error message) how to set up `SCF_LOG_HOST` to get this to work.
Trello: https://trello.com/c/Q7XKcyhx/
> acceptance-tests-brain: syslog: Wait for ContainerCreating

- Jenkinsfile
- bin/common/versions.sh
> Bump fissile stemcell to 12SP3-28.g972190a-0.219

- container-host-files/etc/scf/config/scripts/patches/mapfs_pre_start.sh
Was reaching out to unknown machines, installing an unknown version with a combination of build- and runtime installation. Prevents air-gapped deployment.
Ref: https://trello.com/c/dOiHIcaP/847-5-update-nfs-volume-release-to-176
Installation of the `fuse` package moved into the stemcells, see PR #2251.
This PR modifies the patch for the `mapfs` pre-start script to insert a skip over the installation of the pre-packaged .deb archives when `fuse` support is already installed, instead of inserting the old full installation of `fuse` support via zypper and network.
----
Testing: Build the branch and start the cluster. Run the test suites.
> Replaced the runtime installation of the SUSE userspace `fuse`

- .gitmodules
- Jenkinsfile
- Makefile
- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/sync-integration-tests/spec
- src/scf-release/jobs/sync-integration-tests/templates/config.json.erb
- src/scf-release/jobs/sync-integration-tests/templates/port_forwarding.erb
- src/scf-release/jobs/sync-integration-tests/templates/pre-start.erb
- src/scf-release/jobs/sync-integration-tests/templates/run.erb
- src/scf-release/packages/git/packaging
- src/scf-release/packages/git/spec
- src/scf-release/packages/sync-integration-tests/packaging
- src/scf-release/packages/sync-integration-tests/spec
Adds SITS to run with SCF.
SITS should pass on Jenkins.
> Add SITS - Sync Integration Tests

- Jenkinsfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- make/run
- make/run-eirini
- make/upgrade
- make/upgrade-eirini
Reverts SUSE/scf#2241
Reverting as it needs further discussion on the solution.
> Revert "Use feature flags for autoscaler, cf_usb, credhub, eirini"

- bin/common/versions.sh
Ref: https://trello.com/c/P2Inj8sM/1020-add-feature-flag-details-to-valuesyaml
Associated fissile PR https://github.com/cloudfoundry-incubator/fissile/pull/490 (merged)
Updated to a version of fissile which injects better comments about feature flags into its helm charts.
Check the branch out, run `make vagrant-prep` in a proper vagrant box, then compare the `output/helm` directory against an older saved helm chart from before this change.
> Feature flags comments

- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/src/acceptance-tests-brain/test-scripts/017_syslog_forwarding_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Refactored the syslog forwarding brain test for readability and fixed the wait for the receiver pod to be ready.
Should pass on CI on the various platforms we run brain tests.
> Brain syslog forwarding - refactor and fix wait

- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Ref https://trello.com/c/UL1n6gO0/1007-nfs-persi-brain-failing-on-nightly-caasp3
Additional inspection on exit/failure.
Help debugging brain test issues.
Run brain tests on various platforms.
> Better waiting for nfs test server.

- Jenkinsfile
- container-host-files/etc/scf/config/role-manifest.yml
Use the internal service URL for App Autoscaler to talk to CloudController.
Autoscaler should be deploy-able at SCF installation time.
> Fix autoscaler.cf.api property

- make/include/secrets
Improving the `get_secret` function to catch errors that would avoid issues like https://jenkins-new.howdoi.website/blue/organizations/jenkins/scf/detail/PR-2304/7/pipeline/68.
Should work as before, expect for when it fails, it should be more explicit.
> Improved get_secret

- Jenkinsfile
For consistency, let's enable credhub at deployment time.
Credhub should be deployed successfully.
> Enable credhub on first deployment on Jenkins

- CHANGELOG.md
Commit merge from master (2.16.2)
> Merge from master as 2.16.2

- CHANGELOG.md
- bin/common/versions.sh
> Master to Develop for 2.16.3 CHANGELOG Updates

- container-host-files/etc/scf/config/role-manifest.yml
Attempting to determine if this is causing issues with flakiness during upgrades.
Usual suite of tests (Jenkins, then the QA pipelines).
> role-manifest: revert cf-mysql-release to v36.15.0

- Vagrantfile
The third disk should use port 2, not 1.
Should provision successfully with VirtualBox.
> Fixed VirtualBox third disk port

- README.md
- tooling/bin/check-uaa-clients
- tooling/bin/import-bosh-releases
- tooling/lib/manifest.rb
- tooling/lib/yaml-refinements.rb
Our CF bumping instructions still refer to submodules.
Also, add a script to check UAA clients to help it stay in sync.
Test a bump.
For the UAA client thing: Just run the script.
> Update CF bump instructions

- make/upgrade
Pass `--recreate-pods` to helm upgrade.
The upgrade should recreate all pods.
> Add --recreate-pods to make/upgrade

- README.md
Adding info on bumping CATs in README.
N/A
> Adding info on bumping CATs in README

- Jenkinsfile
- bin/common/versions.sh
> Bump Fissile stemcells

- container-host-files/etc/scf/config/opinions.yml
> Add  skip_ssl_validation back

- deploy/helm/scf/assets/operations/instance_groups/database.yaml
Removed the ephemeral disk for the database and fixed its readiness and liveness probes.
The database should come up and the readiness and liveness probes should work correctly.
> Database fixes

- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/configure-scf/spec
Make fluentd volume paths configurable since we don't know for sure where they live on the node.
> Fix logs on eirini with hostpath

- Jenkinsfile
This PR addresses: https://jira.suse.com/browse/CAP-397 moving the pubish to docker and s3 before deploy stage.
Also, fixed a minor issue with s3 log dump path.
Make sure if the docker images and artifacts were published before deploy stage.
> Jenkins: publishing artifacts before deploy stage

- container-host-files/etc/scf/config/role-manifest.yml
These variables got renamed on https://github.com/SUSE/scf/pull/2390 while moving to PXC.
From the latest release to the current version, any upgrades using these variables shouldn't be affected. Also, not setting them should make no difference in the system.
> Reverted PXC variables renaming

- src/scf-release/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb
> Autoscaler Fix

- container-host-files/etc/scf/config/role-manifest.yml
- make/run-eirini
- src/scf-release/jobs/configure-scf/spec
- src/scf-release/jobs/configure-scf/templates/run.erb
We need to get back to the working eirini bosh release (0.0.4) until we get the latest to work.
> Revert eirini bump

- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/nats.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
- deploy/helm/scf/templates/bosh_deployment.yaml
- deploy/helm/scf/templates/ops.yaml
- dev/minikube/BUILD.bazel
In addition to adding UAA instance group:
- Enabled TLS for the database.
- Improved the overall healthcheck probes.
Pending changes to cf-operator:
https://github.com/cloudfoundry-incubator/cf-operator/pull/379
> Add UAA instance group for the cf-operator

- chart-parts/NOTES.txt
Get straight to the point using a single command.
This is a cosmetic change to NOTES.txt
> cf login instead of cf api

- CHANGELOG.md
- container-host-files/etc/scf/config/role-manifest.yml
and rename eirini-extensions to eirini-persi.
Supersedes #2538
> Bump eirini release to 0.0.9

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
Added the `singleton-blobstore` instance group. It doesn't include the `route_registrar` job.
Deploy and tail the logs from the api instance group. It should output that it can connect to the blobstore successfully.
> Add blobstore to SCF with cf-operator

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
Fix to get CC to connect to the database.
CC should connect to the database.
> Fix ccdb address

- WORKSPACE
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/assets/operations/set_release_urls.yaml
> Bumped cf-deployment to 8.0.0 with cf operator

- dev/kube/klog.sh
Extended `klog.sh` to pull logs from init containers as well.
Beyond that it was mostly good to pull logs from scf v2.
:warning: Had to exclude the `logs` container from CF logs.
This container does not have the `tar` needed (in path) to pull files.
Directory structure changed a bit, to separate init from job containers.
Old hierarchy: `namespace/pod/container`
New hierarchy: `namespace/pod/kind/container`
* Build and run SCF v2.
* Invoke `dev/kube/klog.sh`.
* Confirm that it runs without problem.
* Confirm the presence of pod/`init` directories and containers.
> Extended klog.sh to pull logs from init containers as well.

- dev/README.md
- dev/scf/README.md
Add more documentation on starting SCF for development.
Follow the docs, see SCF deployment start (but probably not finish).
> dev/scf: More docs on spinning up

- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
Fixed UAA hostnames.
NA. UAA will accept connections using the `((deployment-name))-uaa` hostname.
> Fix UAA hostnames

- deploy/helm/scf/assets/operations/instance_groups/router.yaml
Gorouter was not being able to find nats.
Gorouter should show in the logs:
```
{"log_level":1,"timestamp":1563488075.3089044,"message":"setting-up-nats-connection","source":"vcap.gorouter","data":{}}                                                                                           
{"log_level":1,"timestamp":1563488075.3108475,"message":"Successfully-connected-to-nats","source":"vcap.gorouter.nats","data":{"host":"scf-dev-nats:4222"}}
```
> Fixed gorouter connecting to nats

- bosh/releases/pre_render_scripts/api/routing-api/patch_bpm.sh
- deploy/helm/scf/assets/operations/addons.yaml
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/assets/operations/temporary/remove_addons.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
Added routing-api, locket and doppler. It also uses the loggregator addons.
The listed jobs above should come up. (router is still failing and will be handled on a separate PR)
> Add routing-api job to api instance group

- dev/minikube/README.md
Since it doesn't work, it's probably a good idea to tell people not to
use it (until we figure out what's going on and fix it).
Who tests a readme? :p
> dev/minikube: Add note about not using kvm2

- deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
Fixed the adapter readiness probe as the port 8080 is not accessible externally.
The readiness probe should work.
> v3 - Fixed adapter readiness probe

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
- dev/minikube/start.sh
Added `statsd` job to the `api` and `uaa` instance groups.
Check that `statsd` is running and that `cloud_controller_ng` was able to connect to it.
> v3 - Added statsd jobs

- bosh/releases/pre_render_scripts/api/cc_uploader/patch_pre-start.sh
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
Added cc_uploader job to the api instance group.
Check that cc_uploader is running.
> v3 - Added cc_uploader job

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
`policy-server` and `policy-server-internal` should be running.
> Added policy-server and policy-server-internal jobs

- bin/common/versions.sh
> Bump fissile to fix sizing.*.count checks for nil on tiller-2.14+

- def.bzl
As a new version came out, let's use it. :)
> v3 - Bumped Minikube to 1.3.0

- container-host-files/etc/scf/config/role-manifest.yml
See (and also supersedes): https://github.com/SUSE/scf/pull/2664 (CAP-619)
> Add daemonset role for Eirini

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
These fixes enable a docker image to be deployed with cf push. The push returns a failure so far as stats are not reported, but the app is scheduled and is accessible through gorouter.
> v3 - Fixes for cf push docker

- Jenkinsfile
This ensures that nightly builds will get a secret bump when upgrading from the previous release.
- Everything Jenkins should pass
- The resulting build should be version `2.17.1.1` (yes, not semver compliant), which means the secret generator should fill in new secrets relative to `2.17.1`.
> Jenkinsfile: Fake a version bump for nightlies

- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_json.sh
- deploy/helm/scf/assets/operations/addons.yaml
- deploy/helm/scf/assets/operations/certs.yaml
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
This should make `cf push ... -o ...` work without any errors.
Push a docker app.
`cf push ... -o ...`
> v3 - Fixes to make push work e2e

- dev/scf/README.md
The instructions were telling to set DEFAULT_NET_DEVICE, but then hardcoding eth0.
> v3 - Fixed DEFAULT_NET_ADDR to use DEFAULT_NET_DEVICE

- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/jobs/patch_blobstore_pre-start.sh
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
Fixes Blobstore by performing `chown` in the right directories and running it as user 1000 (vcap in the stemcell image).
`cf push` with a buildpack should work.
> v3 - Fixed Blobstore

- CHANGELOG.md
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/opt/scf/bin/recovery-autoscaler-metrics-liquidbase-stale-lock
Merge changes to ```rc``` branch back into ```develop```
> Sync develop branch with rc

- .github/workflows/publish.yml
- .github/workflows/publish/build.sh
- .github/workflows/publish/publish.sh
- .github/workflows/publish/rename.sh
- .github/workflows/publish/verify.sh
This initial pipeline will publish the built tgz chart to https://scf-v3.s3.amazonaws.com/.
> v3 - Add initial Github Actions pipeline for publishing

- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/templates/implicit_vars.yaml
- deploy/helm/scf/values.yaml
This is a fixed-up version of #2705, this time hopefully without breaking the addons.
Everything should deploy correctly.
> jsc#CAP-554: Allow default stemcell to be configured

- deploy/helm/scf/values.yaml
For now, Diego should be the default.
> v3 - Switched from Eirini to Diego as default

- deploy/helm/scf/assets/operations/certs.yaml
- deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/bits.yaml
- deploy/helm/scf/assets/operations/instance_groups/cc-worker.yaml
- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/assets/operations/set_release_urls.yaml
- deploy/helm/scf/templates/implicit_vars.yaml
Removed implicit vars that were used to only render the ops-files.
Instead, used the Helm templating mechanism.
> v3 - Cleaned up implicit vars

- dev/cf_cli/cf_cli.sh
The capture group would return `<none>` and the following condition would return true.
> v3 - Fixed regex on cf-cli script

- dev/minikube/README.md
> v3 - Updated Minikube drivers documentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
add new issues templates for both bug and feature request (enhancement label) and a pull request update to align with feature opportunity expectation.
Can't image how?
> Github issues and pull request templates

- dev/scf/docs/bosh-author.md
[#168498966](https://www.pivotaltracker.com/story/show/168498966)
@aduffeck ping
> V3 bosh author docs

- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/templates/ingress.yaml
- deploy/helm/scf/values.yaml
- dev/scf/docs/installing.md
Added a service to provide external access to the router.
Follow the updated docs.
> v3 - Router service for external access

- container-host-files/etc/scf/config/role-manifest.yml
Our SLE12 based stemcells might generate audit events via libpam.
[jsc#CAP-571]
> Require CAP_AUDIT_WRITE for all containers

- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/cf_usb_helper.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
We're seeing issues where the OSB API endpoint is not reachable, but the pod logs seem to have no issues.  Try getting the state of the resources in the pod to see if e.g. the endpoint is having issues.
jsc#CAP-754
> acceptance-tests-brain: minibroker: get more info on failure

- .gitlab-ci.yml
- .gitlab/pipelines/stages/publish.sh
The job was trying to run the default `minio/mc` entrypoint, which was not the script we provided.
> v3 - Fixed publish step with Gitlab CI

- container-host-files/etc/scf/config/scripts/check_swapaccounting.sh
These are the changes I thought to have been merged with PR https://github.com/SUSE/scf/pull/2877
Except only half (the first commit) looks to be merged, with commit 639c4f83563d675ba169b9cda4414dce68e6da90
This new PR has all the things now, and is looking for proper merge.
Some bad merging seems to have happened, losing part of the changes.
See also https://jira.suse.com/browse/CAP-787
See #2877 
See #2877 
See #2877
> Fix loss of half of PR 2877.

- Jenkinsfile
- bin/dev/create_helm_charts_pr.sh
- bin/image-list.rb
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/override-default-stack.sh
This PR includes all the changes needed in order to have all Eirini images (staging + eirinifs) based on SLE.
Includes scripts used in CI plus the latest image builds.
These changes will also let them be copied over to the final location upon releasing. Will also help users copy the needed images in their private registries for air-gapped installation.
> Add Eirini staging images in the imagelist file

- dev/scf/docs/bosh-author.md
Add permalink to the fissile release-images command
> Add permalink to the fissile command

- CHANGELOG.md
- bin/common/versions.sh
Gearing up for the next scf release
- Changelog reflects changes since 2.18.0
- versions.sh includes reference to CAP 1.5.1
- Next version
> Prep for CAP 1.5.1 RC1 with scf 2.19.0

- CHANGELOG.md
- bin/common/versions.sh
> 2.19.1 RC2 release updates

- src/scf-release/jobs/acceptance-tests/templates/run.erb
- src/scf-release/src/acceptance-tests-brain/test-resources/docker-uploader/main.go
- src/scf-release/src/acceptance-tests-brain/test-scripts/010_insecure_registry_test.rb
This restores the test removed in 30ec5938b2c2ead501a1924f4b4a56136f0a286b and fixes it.
We should have passing tests before we merge (and not just disable them).
Locally, running the test.
It would be better to **cherry-pick my commits and drop the revert** before we merge to `develop`, rather than merge a remove + revert, I think.  But we definitely shouldn't do that if the removal lands on `develop` before this merges.
> Restore insecure registry test

- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/config/blobs.yml
- src/scf-release/jobs/acceptance-tests/spec
- src/scf-release/jobs/acceptance-tests/templates/run.erb
- src/scf-release/packages/golang1.10/packaging
- src/scf-release/packages/golang1.10/spec
- src/scf-release/src/acceptance-tests-brain/test-resources/docker-uploader/main.go
- src/scf-release/src/acceptance-tests-brain/test-scripts/010_insecure_registry_test.rb
This PR intends to add required changes from 12.15 to 12.17 bump. It also fixes failures in CATs.
Changes:
- Bosh release bumps for CF 12.17
Fixes:
- 502 errors due to TLS issues in `log-cache-cf-auth-proxy` job in `log-cache` release
- compilation issues due to golang bump to `1.13.5`
Jenkins and locally on vagrant.
> CF Bump - 12.17 and bug fixes

- container-host-files/etc/scf/config/scripts/patches/uaa_ca_cert_reverse_log_proxy_gateway.sh
Fix develop branch. Patch couldn't be applied anymore
> Fix patch to work with changed upstream code
