- README.md
Because `cf:router` also matches the `tcp-router`
> Anchor pod names at the beginning

- .gitignore
- Vagrantfile
Enable vagrant box to auto-source custom bash definitions on `v ssh` into it.
Extended PATH to make `k` (and other tools) immediately available.
> Auto run bash definitions

- container-host-files/etc/hcf/config/scripts/fetch_uaa_verification_key.sh
- src/hcf-release/jobs/hcf-set-proxy/templates/run.erb
- src/hcf-release/jobs/uaa-create-user/templates/run.erb
https://trello.com/c/8sPDuSg3/174-2-post-deployment-api-routing-api-setup-needs-to-output-something
Role `post-deployment`: `uaa-create-user` - Increase verbosity
- curl more verbose
- retry shows command invoked, explicitly notes success/failure, waiting times
- Extended status messages (added url), fixed typos, normalized to a single form.
Ditto same role job `cf-set-proxy`
Ditto role `api, script `fetch_uaa_...`
> Increased verbosity for p-d-s

- Vagrantfile
- packer/Vagrantfile.template
- packer/http/autoyast.xml
- packer/vagrant-box.json
This makes things a lot faster, especially cloud controller initial migration.
I've already pushed the necessary vagrant box (we can overwrite it if we want changes).
> vagrant: use virtio for libvirt

- packer/vagrant-box.json
This was turned off for development and accidentally left off.  It reduces the image from ~1.4G to ~1.1G.
> packer: enable compact script for qemu

- container-host-files/etc/hcf/config/role-manifest.yml
Further remove duplicate `internal` marker.
> Mark cert for talking to UAA as secret. 

- README.md
https://github.com/SUSE/scf/pull/981 should have fixed the issue (by waiting for UAA before starting routing-api/router).
> README: routing-api/router should come up now

- .envrc
- make/bosh-images
- make/bosh-publish
- make/images
- make/include/registry
- make/kube
- make/show-docker-setup
- make/uaa-certs
- make/uaa-images
- make/uaa-kube
- make/uaa-publish
- make/uaa-run
- make/uaa-stop
- make/vagrant-setup-env
https://trello.com/c/QlFH99Qh/172-2-make-images-and-fissile-build-images-should-be-the-same
Definitions in `.envrc`
Removed now superfluous `make/include/registry`.
Updated all affected make scripts.
Imported equivalent changes for u-f-r.
> Removed `IMAGE_` variables. Now using the proper `FISSILE_` variables.

- Vagrantfile
- packer/http/kubelet-vagrant-overrides.conf
- packer/vagrant-box.json
https://docs.docker.com/engine/userguide/networking/default_network/container-communication/
Trying to connect to the running cf instance from outside the vagrant box fails because of the iptables rules in the box. E.g.
Running `cf api --skip-ssl-validation https://api.cf-dev.io` fails (api.cf-dev.io does resolve to 192.168.77.77). 
I think the above link explains the issue and the solution. We need to `ACCEPT` the FORWARD chain. I'm not sure if this is the right place to set this rule. Also, I only tried this but setting `run: "always"` and running `vagrant reload` to avoid running everything from scratch (described [here](https://www.vagrantup.com/docs/provisioning/basic_usage.html#run-once-or-always)).
> Add iptables rule to allow connecting to docker from outside vagrant box

- make/include/versioning
The original BASH_SOURCE worked, but there's no POSIX way to get the
path to the included file.
> Use GIT_ROOT as $0 refers to the executed script

- Vagrantfile
- packer/http/controller-manager-vagrant-overrides.conf
- packer/vagrant-box.json
This ensures it can delete /tmp/hostpath_pv/* (which are owned by vcap:vcap due to permission issues _inside_ the containers).  Originally this was running as kube:kube.
Fixes #999
> kube: run controller-manager as root

- bin/dev/install_tools.sh
This addresses a bug where NFS mounted files on OSX are owned by the
OSX user which ran `vagrant up`, and cannot be chowned inside the VM
On Linux deployments, certstrap gets owned by root, so needs to be
chowned to the vagrant user
> Avoid chown if owner of certstrap is not root

- bin/dev/versions.sh
- container-host-files/etc/hcf/config/scripts/cf_acceptance_tests_suites.sh
- container-host-files/etc/hcf/config/scripts/configure-nested-net.sh
https://trello.com/c/d0YPQYWg/42-2-fissile-remove-remaining-references-to-hcf-hcp
See https://github.com/SUSE/fissile/pull/250 for the base this adapts too.
Note: This will also be the integration branch when fissile gets merged, i.e. the update to install-tools.
> Genocide hcf references: Update to fissile changes in generated images.

- container-host-files/etc/hcf/config/opinions.yml
- container-host-files/etc/hcf/config/role-manifest.yml
I don't actually know where the `redirect-uri` would ever be used in our setup, so I have no idea if the modified settings make sense or not. They are required to be compatible with uaa-release v35, and SCF works with them applied.
It would be good to know if *all* the redirect URIs should have the `/login` path appended or not...
https://github.com/cloudfoundry/uaa-release/releases/tag/v36
> Starting with UAA bosh release v35 the following ERB validations have
> been added for OAuth Clients:
>
> * redirect-uri is required if authorized-grant-types contains
>   "authorization_code" or "implicit". The redirect uri must be an
>   absolute url and begin with http or https
> Bump uaa-release from v29 to v41

- bin/create-release.sh
The directory name for `dev_releases` is not `dev-releases`.
> create-release: fix typo

- container-host-files/etc/hcf/config/role-manifest.yml
Mysql writes ~2.4GB on startup only, the old default was not enough.
> Increase mysql volume size and bump uaa-fissile-release

- docker-images/cert-generator/scf-cert-generator.sh
**WIP** marker because this is untested. Not because I don;'t want to, given the triviality of the change, but because docker tells me:
```
Unable to find image 'splatform/cert-generator:latest' locally
docker: Error response from daemon: repository splatform/cert-generator not found: does not exist or no pull access.
See 'docker run --help'.
```
IOW I do not have the image locally, and the image is not found on the hub either.
> Ensure that output directory is an absolute path.

- bin/dev/versions.sh
- container-host-files/etc/hcf/config/role-manifest.yml
- make/cats
- make/smoke
A new feature was added to fissile to check this tag. If a bosh-task has
it, it will stop the pod when the test script fails. Without this tag,
kubernetes will restart the pod to try to get the script to finish
successfully.
https://github.com/SUSE/fissile/pull/262
> Add `stop-on-failure` tag to tests

- bin/generate-dev-certs.sh
This is a more inefficient passphrase generation method, but it's not slower in practice (`/dev/urandom` is pretty fast), and drops the requirement of having `xxd` available (which comes with vim).
Note that the `LC_CTYPE` change is necessary for macOS/BSD compatibility (they assume actual text and don't accept random bytes as input).
> Drop use of xxd in cert generation

- packer/http/autoyast.xml
- packer/scripts/install-kubernetes.sh
- packer/vagrant-box.json
This is required for kube-proxy to support hairpin-mode, which is used
by the tcp-emitter to connect to the routing-api.
Also add `man` to the Vagrantbox.
> Add kubenet to our kubernetes setup

- src/hcf-release/src/acceptance-tests-brain/test-resources/node-env/package.json
That way we don't have to modify the tests whenever the assets bundled
with the nodejs-buildpack change.
> Unpin node version in test app

- bin/settings/settings.env
- container-host-files/etc/hcf/config/role-manifest.yml
`overlay-xfs` doesn't work on all SUSE kernels
> Make btrfs the default grootfs driver

- .envrc
Necessary in CI (because we don't want to automatically download fissile but use the CI-approved version instead).
> .envrc: don't override FISSILE_BINARY, HCF_PACKAGE_COMPILATION_CACHE

- README.md
helm charts are generated in the `images` step, called by `vagrant-prep`
> Remove reference to `make helm`

- packer/scripts/install-kubernetes.sh
Ad keep the kernel at 4.4, which is what CaaSP is using.
We no longer use overlay-xfs, but just btrsfs now.
> Pin kubernetes to version 1.6.1

- Vagrantfile
- container-host-files/etc/hcf/config/role-manifest.yml
- container-host-files/etc/hcf/config/scripts/patches/fix_tcp_routing_wait_for_uaa.sh
The tcp-router does not recover from starting up without a valid UAA token.
WIP: The tcp-router also requires an update to the vagrant-box 2.0.5 to enable hairpin NAT.
Update the Vagrant file once https://github.com/SUSE/scf/pull/1052 has been merged
> Make sure the tcp-router waits for UAA to be available

- container-host-files/etc/hcf/config/scripts/configure-HA-hosts.sh
Tested locally, roles come up and 🚬 passes
> patches: configure-HA-hosts: fix typo

- container-host-files/etc/hcf/config/role-manifest.yml
Also mount /var/vcap/data, so there's enough room for grootfs data, and it doesn't get stored on the container's volume.
> Increase size of data volume for garden

- container-host-files/etc/hcf/config/opinions.yml
- container-host-files/etc/hcf/config/role-manifest.yml
because we don't deploy the dashboard, but the client may end up being
not unique:
```
Creating service broker mysql-dev as admin...
FAILED
Server error, status code: 502, error code: 270012, message: Service broker catalog is invalid:
Service mysql-dev
Service dashboard client id must be unique
Service broker already exists - updating broker
```
> Remove cc-service-dashboards UAA client

- container-host-files/etc/hcf/config/role-manifest.yml
Using the same tag will mount the same volume to both locations.
> Use different tags on the diego-cell volume claims

- Chart.yaml
- container-host-files/etc/hcf/config/role-manifest.yml
https://trello.com/c/cgfrMMuD/288-fix-version-number-in-v2-info
Subordinate PR: https://github.com/SUSE/uaa-fissile-release/pull/38
(Fix of version information in the helm charts, per @jandubois 's request in RC)
> Bump the SCF version number for the alpha release.

- bin/dev/kube-ready-state-check.sh
Ref: https://trello.com/c/cCgf3Rsr/271-1-ci-kube-ready-state-checksh-must-include-tiller-install-check
Tweaked the messages a bit.
Testing:
- On a (newly-made) vagrant box the check should succeed without any special work.
- For testing the other side `helm reset --force` uninstalls tiller. After that the check should fail.
- And redoing `helm init` should make it succeed again (after a while, tiller takes a bit to be fully running).
> Added test for tiller to the readiness checker.

- .envrc
- bin/cert-generator-wrapper.sh.in
- bin/create-release.sh
- bin/dev/install_tools.sh
- bin/dev/vagrant-envrc
- bin/generate-dev-certs.sh
- bin/init-host-for-vagrant.sh
- bin/validation.sh
https://trello.com/c/FTwkoGmF/297-unset-cdpath-in-certgen-script
The construct broke due to ev `CDPATH` causing the `cd` to generate additional output.
Instead of removing `CDPATH` the `readlink` gives us the same functionality without hassle.
Eight more places.
(Note: Currently unable to test myself, the local concourse blocks me from playing with vagrant).
> Replaced `cd/pwd` construct to get absolute path with `readlink -f`.

- Jenkinsfile
Jenkins should be configured to use a multi-branch pipeline. Automatically triggering builds on commit is optional.
This uses the new Jenkins pipeline format (because it's actually advanced enough to do so now), and only goes up to publishing everything (no deploys).
> Add Jenkinsfile for experimental Jenkins-based builds

- bin/dev/install_tools.sh
This is needed to let the bash (running as a different user) see the variable, later in the script.
> install_tools: export SCF_BIN_DIR

- Jenkinsfile
Combined with `disableConcurrentBuilds()` this lets us save on disk space by re-using previous builds.
> jenkins: force use a fixed workspace

- Jenkinsfile
This means automated builds can actually publish correctly
> jenkins: use the correct s3 bucket

- Jenkinsfile
Also fixes an issue with jenkins deleting files that don't exist
> bump uaa-fissile-release for certstrap changes

- Vagrantfile
`output/` survives across Vagrant boxes, so this allows the bash history to be shared between runs of vagrant.
> Cache bash history

- .gitmodules
Jenkins does not currently use SSH to check out (and has no key to do so with).
> cf-usb: switch to https for git repo

- bin/generate-dev-certs.sh
The bash on darwin is too old to support dynamic fd creation; work around this by using temporary files instead.
> generate-dev-certs: fix for darwin

- bin/dev/kube-ready-state-check.sh
kube category do not need ntpd or systemd-timesyncd check. This check if run from local machine or a container with  proper kube config might fail, because that machine might not have these running. This is not a requirement.
> remove ntpd check for kube category in kube-ready-state-check.sh

- Vagrantfile
- packer/http/autoyast.xml
- packer/http/controller-manager-jenkins-overrides.conf
- packer/http/data-hostpath-create.service
- packer/http/tmp-hostpath_pv.automount
- packer/http/tmp-hostpath_pv.mount
- packer/http/user-limits.conf
- packer/scripts/create-kube-certs.sh
- packer/vagrant-box.json
Triton uses a different base image, so we need to add the vagrant user and install helm separately. We also need Java for Jenkins.  Since it requires a secondary disk for bulk storage, we need a bunch of systemd units to line things up correctly to ensure we mount the hostpath stuff on that disk.
> Packer: support building Jenkins slaves on Triton

- Vagrantfile
- packer/scripts/install-kubernetes.sh
- packer/vagrant-box.json
It was previously all in the `cni` package, which is required by docker. It's now split into a separate package, and is required to run kubelet.
> kube: install cni-plugins

- Jenkinsfile
Trying to do a checkout seems to confuse jenkins and that step just fails silently.
Instead, we can just delete the directory and pretend we're not skipping checkout.
> jenkins: fix wiping the repo

- bin/common/versions.sh
In this version the new writer is only used for helm/values.yaml
and helm/templates/secret.yaml.
> Bump fissile version to use new config writer

- container-host-files/etc/hcf/config/role-manifest.yml
This also includes using `KUBE_SIZING_*_COOUNT` variables to trigger a reconfiguration for roles that need to be directly aware of all members of clustered roles.
> Update sizing configurations for some of the roles

- Makefile
This ensures that we will re-download fissile when a different version is desired.
> makefile: make fissile depend on versions.sh

- container-host-files/etc/hcf/config/role-manifest.yml
This PR has no trello ticket associated with it.
It grew out of work on https://trello.com/c/AK24MJA3/235-3-scf-config-reckoning
while testing changes and having to run only a subset of the :cat:
> Properly define parameter for CATs testsuites to get user settings (if made) into the system.

- bin/common/versions.sh
- make/kube
Also needs a change to make/kube because "Pods" in kube configs is
now inside quotes and the apiVersion is now a template expression
for helm charts.
> Bump fissile for affinity declaration support

- Jenkinsfile
Jenkins didn't seem to like the old way (threw exception).
> jenkins: fix wiping by not assigning to params

- bin/config-validator.rb
- bin/vagrant-setup/common.rb
The ca.env file may not exist at the time validation is being run, and this should not break validation.
> D5GZQLOg Fix validation errors due to missing bin/settings/kube/*.env files

- bin/common/versions.sh
- bin/create-release.sh
- bin/dev/install_tools.sh
- bin/validation.sh
This makes it easier to co-ordinate changes to the `bosh-cli` image.
This requires a UAA bump for SUSE/uaa-fissile-release#48
> create-release: pin bosh-cli docker image version

- container-host-files/etc/hcf/config/role-manifest.yml
Kubernetes 1.7+ requires this key, it was optional in earlier versions.
> Add topologyKey to affinity rules

- bin/dev/install_tools.sh
- bin/generate-dev-certs.sh
On Jenkins (master only), the default shell is `/bin/false`, so we never launch bash directly, and `${HOME}/bin` doesn't seem to get set as part of `${PATH}` correctly.  Try to remedy that by copying the logic from UAA's `generate-certs.sh` over.
> generate-dev-certs: stop trying to find certstrap

- .envrc
- bin/cert-generator-wrapper.sh.in
- bin/common/install_tools.sh
- bin/common/versions.sh
- bin/create-release.sh
- bin/dev/install_tools.sh
- bin/generate-dev-certs.sh
- bin/init-host-for-vagrant.sh
- bin/validation.sh
- container-host-files/etc/hcf/config/role-manifest.yml
- container-host-files/etc/hcf/config/scripts/patches/fix_etcd_cluster_hostnames.sh
Also bumps UAA for same
Depends on related PRs:
SUSE/cloudfoundry#57
SUSE/uaa-fissile-release#47
SUSE/fissile#283 (to handle releases with zero packages)
Should probably co-ordinate between all four (especially for the docker image change for `splatform/bosh-cli`).  This one will need an updated uaa-fissile-release (on the merge) and the fissile version string.
> create-release: bosh v2 compat

- Jenkinsfile
This allows for publishing the SLE stemcell to the staging registry but
not to S3. 
**NOTE:** The publish stage in the pipeline has been replaced by two stages (publish-docker and publish-s3). When merging this the jenkins triggers have to be adapted to this new pipeline layout.
> Split publish step into publish-docker and publish-s3

- bin/dev/kube-ready-state-check.sh
The test for kube storageclasses was broken for CaaSP2, when kubectl returns e.g. 3 lines of info in the beginning in general:
```
> ./kube-ready-state-check.sh kube
Testing kube
...
Verified: A storage class should exist in K8s
```
but that's not true, since there is no storage class:
```
> kubectl get storageclasses
2017-10-11 09:48:27.380930 I | proto: duplicate proto type registered: google.protobuf.Any
2017-10-11 09:48:27.380992 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-10-11 09:48:27.381007 I | proto: duplicate proto type registered: google.protobuf.Timestamp
No resources found.
```
The fix is to return "0" when the output does not contain "No resources found.".
> Improve test for kube storage classes

- container-host-files/etc/hcf/config/opinions.yml
@troytop wrote: "sle12 looks better"
https://chat.microfocus.net/channel/suse-paas?msg=Rur4HZfEkhPfZRDY9
This only changes the user-visible name. We could also change the package name inside cf-sle12-release, but doesn't really feel necessary.
Tested with Vagrant box:
```
$ cf stacks
...
name         description
cflinuxfs2   Cloud Foundry Linux-based filesystem
opensuse42   openSUSE-based filesystem
sle12        SLE-based filesystem
$ cf push -s sle12
Using stack sle12...
...
$ cf ssh my-app -c "cat /etc/os-release" | grep PRETTY
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
```
> Rename cf-sle12 stack to just sle12

- Jenkinsfile
I think we turned this on for the wrong reasons. Jenkins is now largely
idle despite having build queues backed up. Trying out removing this.
> Enable concurrent builds again in Jenkins

- container-host-files/etc/hcf/config/role-manifest.yml
- make/run
Not sure why HA requires 3 Diego cells, but that's what it says on
https://docs.cloudfoundry.org/concepts/high-availability.html
> Add minimum HA counts to the role manifest

- Jenkinsfile
This makes it easier to test restarting slaves &c.
> Jenkinsfile: Add ability to manually add node labels

- bin/dev/legalscan.sh
The submit request should automatically trigger legaldb because
its user is setup as reviewer for the `:reviewed` projects.
> Adapt legalscan to suggested submit request approach

- bin/common/versions.sh
- container-host-files/etc/hcf/config/role-manifest.yml
This is needed for fissile to correctly construct the links.
This is currently marked WIP because it only becomes useful after SUSE/fissile#288 and SUSE/configgin#59 land, but can be used to test those PRs with.  This is required for the fissile bump (because otherwise fissile will spit out new errors on not having links).
> role-manifest: explicitly mark exported bosh links

- Jenkinsfile
`grep '-scf|-uaa'` looks too much like a grep option; prefix -- to make sure it gets treated as a pattern so we actually do useful things there
> Jenkins: make grep not confuse pattern with options

- bin/common/install_tools.sh
- Something happens in OpenSUSE 42.3 where sudo'd things are not having
their $PATH set to the correct thing leading to a missing 'helm' binary.
This will be useful later when we upgrade the vagrant box to 42.3.
> Fix an issue where helm could not be found

- container-host-files/etc/hcf/config/role-manifest.yml
5GB is too little, especially with large buildpacks compiled for multiple stacks
> Increase default volume size for the blobstore

- bin/dev/legalscan.sh
Hi,
this change creates for each package it's own submit request. It automatically supersedes the old SR when needed :) There is no need to checkout the project, the script can be executed anywhere.
For unknown reasons the approach with `osc submitrequest --seperate-requests $PROJECT:reviewed` doesn't work.
Jonathan
> Create separate submit request for each package

- bin/common/versions.sh
This changes behaviour such that we will run bootstrap on any pod where it is the only pod with a given image version.  This is to support upgrades and similar scenarios where the image versions will change, but not necessarily starting from the lowest-numbered pod.
> Bump stemcell version for configgin 0.14.0

- make/include/versioning
- make/show-versions
We don't need GIT_PREREL, everything is controlled from the git tag.
> Get rid of GIT_PREREL

- Jenkinsfile
This dumps out the docker/kube/helm state on cleanup exit (success or failure), to try to figure out what state things are in and why our current attempts to catch problems aren't working
> Jenkinsfile: Try to track down cleanup errors

- Jenkinsfile
The structure of the helm chart bundle changed; it now includes a "-opensuse" suffix.  Fix the scripts to be able to find the correct files.
> Jenkinsfile: fix deployment / test run

- Jenkinsfile
This fixes deploying SCF on the test kube (probably)
> jenkins: refer to pipeline param as $param.*

- container-host-files/etc/hcf/config/opinions.yml
- src/hcf-release/jobs/uaa-create-user/spec
- src/hcf-release/jobs/uaa-create-user/templates/run.erb
Fix 3 issues for new UAA release:
1,  use `404` instead of `404 not found` to check if identity-zone exists, or will report error because UAA message change.
2, Add cloud_controller.read and cloud_controller.write groups for new identity-zone, because new UAA release remove them that new user cannot use CC (Report Invaild Token Error):
https://github.com/cloudfoundry/uaa-release/releases/tag/v43
3, We need to discuss the third change, because I change it in run.erb to use `set +e` and `set -e` to ignore the error, because `openid` is the default group, when you add admin to group openid, the process of post-deployment-setup will report and fail in the end:
```
api/0:/# uaac member add 'openid' admin
error response:
{
"error_description": "Trying to add member to default group",
"error": …
```
> Fix new UAA release 3 migration issues

- make/kube
We actually handle the different versions of things via helm templating; the ugly hack to fix up the version isn't necessary there.
> make/kube: Don't to apiVersion hack when doing helm

- container-host-files/etc/hcf/config/role-manifest.yml
- container-host-files/etc/hcf/config/scripts/patches/fix_blobstore_send_timeout.sh
Currently our buildpacks contains assets for 3 different stacks, and on some slower test deployments they fail to upload within the default 2 min allowed by HTTPClient.
> Increase send_timeout for blobstore uploads from 2 to 6 min

- .envrc
- .gitignore
- Jenkinsfile
- README.md
- make/bundle-dist
- make/kube
- make/kube-dist
- make/run
- make/tests
This moves all the generated files into `output/` instead of being at the top level. This makes it easier to check in files that we want to include verbatim inside the helm chart dist bundles later.
> `make kube` / `make helm` / `make dist` should output into output/

- make/clean
When deleting obsolete images, we will ask fissile for images it does still care about.  But since we just deleted fissile, that will (probably) fall over.
> make/clean: Use fissile before we delete it

- container-host-files/opt/hcf/bin/pod-status
We previously used awk to find the right field to check for readiness. Unfortunately, this meant that the columns were all changed, and we had to run `column -t` on it; this doesn't work well if any of the columns had whitespace within it (e.g. when the pod status had a longer explanation on why it wasn't working).
This switches to using a perl one-liner that doesn't affect the column layout, so that issue does not occur.
> pod-status: don't re-column the output

- container-host-files/etc/hcf/config/scripts/configure-HA-hosts.sh
SCF should check error in this script. in my environment, I don't have kube serviceaccount, so if I cannot get `k8s_api apis/apps/v1beta1` for replicas, the error will be skipped. then some of statefulset pods may work incorrectly, such as consul and nats. Without set -e, the pod will be started without any error exit, but user don't know why CF function doesn't work fine.
> Fix configure-HA-hosts k8s_api error issue 

- Jenkinsfile
It looks like we can end up containers that have been created but never actually run.  This is likely due to errors that get kube pods to not run at all (e.g. missing secrets).  We should clean those up too, so that we eventually reclaim the resources.
> Jenkins: Cleanup: Removed created, never-run, containers

- Jenkinsfile
We attempt to find test files by shell glob.  When doing so, do not quote the shell glob, as that means it will not be expanded by the shell (causing the files describing the thing we are looking for to not be found).
> Jenkins: Don't quote shell globs when looking for test files

- Jenkinsfile
It appears that nip.io has been down for > 12 hours. Try the fallback service instead.
> Jenkins: switch to xip.io instead of nip.io

- bin/common/versions.sh
Pulls in change to use rolling update in helm charts
I'm sad because we're using fissile that's not off the master branch.
> fissile: bump version

- Jenkinsfile
This reverts commit 298b44ef40813f78b8d4121f8d0283d2fdc24d6c.
> Revert "Jenkins: switch to xip.io instead of nip.io"

- container-host-files/etc/scf/config/role-manifest.yml
This is required for HA (for the pods to find the other instances).
> role-manifest: allow apps.statefulset/get to configgin roles

- make/include/versioning
- make/kube
https://trello.com/c/hu6x06Qz/507-helm-unsightly-versions
Move the extended version information to the `apiVersion` key, and show only the `GIT_TAG` in the `version` key, to make the version information shown by the helm tools more sightly.
Ditto for UAA chart = https://github.com/SUSE/uaa-fissile-release/pull/70
> More sightly helm version

- container-host-files/etc/scf/config/role-manifest.yml
When HA is set, we never updated the counts in helm; this means that the secret generator didn't know about the correct counts, and therefore did not generate certs which would apply to all the nodes in self-clustering roles.  This fixes the issue by changing the secret generator to create wildcard certificates (limited to the appropriate kubernetes headless services for each role).  We also drop most of the sizing variables as they are no longer necessary due to the above change.
Marking WIP to wait for SUSE/uaa-fissile-release#71
> Fix mutual TLS certs when HA mode is true

- .envrc
- Jenkinsfile
- bin/common/versions.sh
This PR removes the text fields from the Jenkinsfile, instead using a flag to switch between OpenSUSE and SLES.
It retains the environment variable overrides so a dev can still easily switch stemcells without changing files in the repo.
Note that you need to provide a valid Docker repository and credentials for SLES builds as it's not on Docker Hub.
> Don't set stemcell via jenkins environment

- .envrc
- Jenkinsfile
- README.md
- bin/common/versions.sh
- make/kube
Generating a build with a different base for the stack and stemcell
doesn't make sense.
> Use a single flag in Jenkins for stack and stemcell

- bin/common/versions.sh
- make/compile
Also update the compile cache script to support it. This is needed to ensure that we will rebuild packages when the stemcell changes (e.g. when we change distros)
We don't attempt to support migrating the old caches over because it is unknown if those were compiled correctly.
> Fissile: Update to use stemcell in compile directory

- container-host-files/etc/scf/config/scripts/cf_acceptance_tests_suites.sh
- src/scf-helper-release/jobs/acceptance-tests/templates/pre-start.erb
The default configuration we use for vagrant boxes uses a private network address (192.168.77.77) for the external endpoint for the CF cluster.  This means that it is not covered by the public networks default security group, and therefore apps won't be allowed to connect to it.  This breaks the route services test where it attempts to connect to an exposed port from within a different application.
> CATS pre-start: explicitly add SG for endpoint

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_duplicate_buildpack_positions.sh
There are 2 local worker processes adding buildpacks and Sequel::Plugins::List is not concurrency-safe, so add a lock for updating the `position` value when the new record is created.
> RVRbC8mE Avoid race condition while adding admin buildpacks

- .gitmodules
Hi,
diego-release and routing-release moved from the cloudfoundry-incubator to the cloudfoundry project. We didn't  noticed that because they redirect to the new place.
Jonathan
> Update repository links in gitmodules

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/nfs_volume_libdir.sh
SUSE uses `/usr/lib64` instead of `/usr/lib` (or the Debian-multiarch style `/usr/lib/x86_64-linux-gnu`).  So we need to change how the diego-cell install script installs the nfs libs we compiled from source.
> cell: Change where we copy nfs libs so they work for SUSE

- container-host-files/etc/scf/config/opinions.yml
https://trello.com/c/MWgYpR8T/523-cats-fuse-endpoint
SCF does not support that, so they should not be run.
Example of a test breaking without privileges is `apps/fuse.go`.
> Disable test based on privileged containers.

- container-host-files/etc/scf/config/opinions.yml
We don't have the cf-networking release, so these tests shouldn't run.
> Disable container networking tests

- Jenkinsfile
This PR adds a link to the cap-release-tool to the output of the scf build on Jenkins.
Which will allow for publishing signed docker images to the public registry.
> Add link to cap release tool to the build output.

- src/scf-helper-release/jobs/acceptance-tests/templates/run.erb
This lets people peek in on an in-progress run (e.g. on Jenkins) to let them know that things are still going and aren't stuck.
> CATS: Show the log as it happens, instead of after the run

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/cc_clock_wait_for_api_ready.sh
This prevents the cc-clock role from creating the schema_migrations
table when it tries to check for the existence of this table. Under
heavy load, it can be deadlocked trying to access this table, and fail
to find it. Afterwards, it will try to create the table, and could
deadlock the migration happening in the api role.
https://github.com/jeremyevans/sequel/blob/7995642c7fccdf1d8a8516cdf3d51db2859bb27e/lib/sequel/extensions/migration.rb#L768
> Make the cc-clock role wait until the api is ready

- bin/common/versions.sh
This PR bumps fissile stemcell versions for SLE and openSUSE to fix missing arp binaries.
> Bump fissile stemcell versions

- README.md
Remove the very outdated info on direct Kubernetes install with a direct link to working wiki instructions.
> Update Readme to note working Kubernetes install

- bin/common/versions.sh
Ref: https://trello.com/c/6925zx7v/584-2-cpu-being-able-to-enable-cpu-limits-whilst-leaving-them-off-by-default
Note, no changes to the role manifest.
We keep the existing request info, and off by default for dev.
> Bump the fissile version to include handling of cpu limits.

- container-host-files/etc/scf/config/role-manifest.yml
The current recommendation is that mysql-proxy behind a load balancer is
ok because each instance will point to the same mysql DB instance.
> Allow mysql-proxy to use multiple instances

- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/jnGQ3xAo/610-2-make-gorouter-configurable-for-routerforwardedclientcert
Vagrant: Builds ok, passes :smoking:, brain, and :cat:
> Expose property `router.forwarded_client_cert` as parameter `ROUTER_FORWARDED_CLIENT_CERT`.

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_monit_rsyslog.sh
Hi,
In nats or doppler, only limited logs will be recorded to /var/log/messages, then this file is no longer updated. If /var/log/messages is outdated for more than 65 mins, there will be an alert named "timestamp failed". So add a patch for these component to remove the check.
[issue 1433](https://github.com/SUSE/scf/issues/1433)
Thanks!
> Add a patch to remove timestamp check for rsyslog

- packer/Makefile
- packer/http/autoyast.xml.tpl
- packer/http/kubelet-vagrant-overrides.env
- packer/scripts/create-kube-certs.sh
- packer/scripts/install-cap-archives.sh
- packer/scripts/install-kubernetes.sh
- packer/vagrant-box.json
The cached libvirt box no longer builds, because we now need more RAM to install `kernel-default`. Not sure why; guessing it downloads the RPM to a ramdisk?
Of course, this leads to Fun like discovering that the repo we used no longer exists… so I had to upgrade kubernetes to get it to build.
> update cached libvirt box

- src/scf-helper-release/src/acceptance-tests-brain/test-scripts/008_cf_usb_test.sh
It looks like MySQL 8.0.4+ defaults to using SHA2 for password auth, which older clients might not support.  Trying to use 8.0.3 (which uses the old native password auth) to see if that helps.
> Use MySQL 8.0.3 to attempt to troubleshoot errors

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
HA configurations of MySQL can take a long time to respond when starting
up on slower hardware, so allow users to increase this timeout if
needed.
> Make mysql-proxy healthcheck timeout configurable

- container-host-files/opt/scf/bin/klog.sh
* shellcheck linting
* Simplify klog by removing error checks. This will be handled by another tool in the future.
* Don't remove this pod suffix - this was overwriting log files if there was more than one pod.
* Get some extra kube logs related to each pod and the overall namespace
> Cleanup klog.sh debugging script

- bin/dev/create_helm_charts_pr.sh
The problem with the username password combination is that each time a
new access token is created which does not make sense for ci.
Similar to https://raw.githubusercontent.com/SUSE/cf-usb-sidecar/develop/scripts/create_helm_charts_pr.sh .
Maybe we should combine them in the future.
> Adapt create_helm_charts_pr.sh to allow Github tokens

- bin/fissile
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_mysql_advertise_ip.sh
We can have fewer immutable secrets (if we upgrade cf-mysql); with just 4 left we can still run an upgrade (with a new secret generation number) and still have the cluster settle to a usable state.
UAA changes are still pending; it is not yet obvious how we'll be able to carry the UAA changes to SCF.
> Reduce the number of immutable secrets

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Set up hostpath mounts to `/sys/fs/cgroup` on diego-cell so that garden can correctly create cgroups at the global level (because docker doesn't isolate things correctly).  This fixes issues with memory accounting in the Kubernetes dashboard.
See:
- https://github.com/SUSE/scf/issues/1345
- https://github.com/cloudfoundry/guardian/pull/110
- https://github.com/moby/moby/issues/34584
> Set up cgroups mount for diego-cell

- Vagrantfile
- bin/common/install_tools.sh
- packer/Makefile
- packer/scripts/create-kubedns.sh
- packer/scripts/install-helm.sh
- packer/scripts/setup-service-account.sh
- packer/scripts/wait-for-kube.sh
- packer/vagrant-box.json
This just rebuilds the vagrant box, because I already had kube `1.9.6+9f8ebd17` for the cached vagrant box work.  Of course, that comes with issues with actually building the things…
Relevant boxes already uploaded to S3.
> Update vagrant box to kube 1.9

- Jenkinsfile
With single quotes the os part of the glob is not interpolated resulting
in an empty file array and a subsequent build failure.
> Fix string interpolation in Jenkinsfile

- CHANGELOG.md
Based on discussion, any CF bump should mean a minor release version bump. Thus, the past check-in should've already raised the version up, so this tag is for catching up.
> Merge from master as 2.9.0

- Jenkinsfile
- Makefile
> Jenkins: Don't run `make clean` when tarring up sources

- bin/common/versions.sh
Ref https://trello.com/c/BxUbBojW/642-5-eks-label-for-specific-pods-that-require-more-privileges-than-default
Ref https://github.com/SUSE/fissile/wiki/Operator-overrides-of-role-capabilities
Controlling fissile PR https://github.com/SUSE/fissile/pull/351
> Enable operator overrides for role capabilities

- make/include/secrets
This PR fixed issue [1528](https://github.com/SUSE/scf/issues/1528).
> Fetch secret name/key from first matched pod

- make/uaa-wait
- make/wait
Hi,
This PR fixes [issue 1522](https://github.com/SUSE/scf/issues/1522).
> Exclude completed jobs when waiting pods ready in kube 1.9

- container-host-files/etc/scf/config/role-manifest.yml
These secrets are things where we need to keep the old value around to decrypt the old data. They need to be kept immutable, until we have a better way of rotating them (plus the CCDB encryption key).
Fixes boo#1092990
Manually checked against the remaining secrets:
```sh
for i in $(
y2j < container-host-files/etc/scf/config/role-manifest.yml | \
jq -cSr '
.configuration.variables[] | 
select(.secret) | 
select(.immutable | not) | 
select(.generator) | 
select([.generator.type] | inside(["Certificate", "SSH", "CACertificate"]) | not) | 
.name
' )
do
printf "%b%s%b\n" "\e[0;1;33m" "$i" "\e[0m"
grep --color=always -w $i container-host-files/etc/scf/config/role-manifest.yml
done | less -R
```
> role manifest: Mark rotateable secrets as immutable

- make/include/secrets
The base64 command on Linux.
```
~# base64 --help
Usage: base64 [OPTION]... [FILE]
Base64 encode or decode FILE, or standard input, to standard output.
Mandatory arguments to long options are mandatory for short options too.
-d, --decode          decode data
-i, --ignore-garbage  when decoding, ignore non-alphabet characters
-w, --wrap=COLS       wrap encoded lines after COLS character (default 76).
Use 0 to disable line wrapping
--help     display this help and exit
--version  output version information and exit
```
The base64 command on Darwin.
```
$ base64 -h
base64: invalid option -- h
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
-h, --help     display this message
-D, --decode   decodes input
-b, --break    break encoded string into num character lines
-i, --input …
```
> fix base64 option for Darwin

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_cfdot_properties.sh
cfdot is a commandline tool to interact with the diego components, primarily with the BBS. It is useful for debugging.
https://github.com/cloudfoundry/cfdot
https://discuss.pivotal.io/hc/en-us/articles/115004883487-How-to-use-Cloud-Foundry-CF-Diego-Operator-Toolkit-CFDOT-
The changes in scf-helper-release are temporary and should be reverted when upstream adds the properties to make the BBS and locket endpoints configurable.
[trello#PB3FPK2V]
> Add cfdot job to all diego roles

- container-host-files/etc/scf/config/role-manifest.yml
We don't actually _need_ consul right now, so it should have a minimum of zero.
> role-manifest: consul: set min to 0

- bin/config-validator.rb
- container-host-files/etc/scf/config/role-manifest.yml
Update role manifest validation to let the secrets generator use
KUBE_SERVICE_DOMAIN_SUFFIX without configuring HA itself.
[trello#PGGWWyht]
> Bump scf-secrets-generator to make cert expiration configurable

- container-host-files/etc/scf/config/role-manifest.yml
For consistency, and so we can deprecate the old syntax.
> role manifest: postgres: use new volume syntax

- .gitmodules
- README.md
- bin/update-releases.sh
- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
- Ref: https://trello.com/c/T90U8E4Z/674-5-bump-cf-and-uaa
- Subordinate UAA PR = https://github.com/SUSE/uaa-fissile-release/pull/103
- Skipping garden changes because we have to support `btrfs`, and recent upstream releases do not anymore.
- Passed :smoking:, brain, and :cat: on local vagrant. Lets see what jenkins thinks of it.
- Passed Jenkins as well.
- :warning: Uses a fork of the 1.36 :cat: to fix an issue with a new test checking BPs for version information. Our BPs are not caught up and do not provide the version info, breaking the test.
> CF Bump to v 1.35, skipping garden changes

- container-host-files/etc/scf/config/role-manifest.yml
Despite the claim in the description, it was defaulting to the empty string before, generating invalid URLs.
[trello#DHeMriNz]
> Set SCF_LOG_PORT default to 514

- make/uaa-wait
- make/wait
Hi,
Our wait/uaa-wait scripts was still not good for check. 
Sometime, pod status like below would stop waiting and continue to deploy process :
```
NAME                        READY     STATUS      RESTARTS   AGE
diego-cell-0              1/1       Terminating 0          5m
```
So I added a condition `((match($2, /^([0-9]+)\/([0-9]+)$/, c) && c[1] != c[2] && !match($3, /Completed/)) || !match($3, /STATUS|Completed|Running/))` to verify pod status:
1. Condition 1 `(match($2, /^([0-9]+)\/([0-9]+)$/, c) && c[1] != c[2] && !match($3, /Completed/)`: verify pods' containers readiness and exclude job pods.
2. Condition 2 `!match($3, /STATUS|Completed|Running/))`: verify pods' status
Please help to review. Thanks!
> Verify pod status in pod waiting pharse

- container-host-files/etc/scf/config/role-manifest.yml
The active/passive work caused the `cc-worker` role to trigger this bug, but we don't need to be monitoring `/var/log/messages` in any of our roles because we don't rely on that log file as much as BOSH.
> Add monit_rsyslog timestamp patch fix to all roles

- .gitmodules
- Local vagrant had lots of :cat: failures (76)
- While one of them was for the test of interest it looks to be a timeout waiting for things to get ready. Not the actual condition of interest.
- While will redo locally, also made the PR to run :cat: via jenkins.
The redo went down to 3 failures, none of which are about the buildpacks.
So, we can switch back, the updated go/ruby buildpacks pass the new tests now.
> With go/ruby buildpcks updated, switch CATs back to upstream.

- Makefile
- make/asg
- make/assets/nfs-provisioner/claim.yaml
- make/assets/nfs-provisioner/class.yaml
- make/assets/nfs-provisioner/clusterrole.yaml
- make/assets/nfs-provisioner/clusterrolebinding.yaml
- make/assets/nfs-provisioner/deployment.yaml
- make/assets/nfs-provisioner/psp.yaml
- make/assets/nfs-provisioner/serviceaccount.yaml
- make/deploy-mysql
- make/helm-suse-repository
- make/nfs-storageclass
- make/test-service
- make/usb-plugin
Ref https://trello.com/c/UMCUmJUf/700-vagrant-service-automation-mysql
Similar to usb-deploy.sh in the qa-pipelines of cf-ci.
Differences:
- mysql only
- Various pre/post tasks factored into their own scripts.
> Scripts and assets to automate the deployment of the mysql sidecar helm chart in a vagrant box.

- bin/common/versions.sh
- bin/dev/install_tools.sh
- container-host-files/etc/scf/config/role-manifest.yml
This implements the active/passive work.
Note that `mysql-proxy` isn't actually active/passive; it _should_ be, but it _actually_ is just enabled everywhere because [switchboard](https://github.com/cloudfoundry-incubator/switchboard/) doesn't implement any locking.
> Rework pod management

- README.md
- bin/common/versions.sh
Forgotten during the actual bump of the sources. 
Updated instructions in the README.md
> Bump the CF version information

- Jenkinsfile
Sample message:
```
Return-path: <notifications@example.invalid>
Received: from jenkins.example.invalid (localhost [127.0.0.1])
by localhost (Postfix) with ESMTP id 675A022A74
for <notifications@example.invalid>; Tue,  5 Jun 2018 20:39:27 +0000 (UTC)
Date: Tue, 5 Jun 2018 20:39:27 +0000 (UTC)
From: notifications@example.invalid
To: notifications@example.invalid
Message-ID: <1398547267.17.1528231167421.JavaMail.jenkins@ip-192-0-2-55>
Subject: Jenkins failure: scf/PR-1576 #29
MIME-Version: 1.0
Content-Type: multipart/mixed; 
boundary="----=_Part_16_281734322.1528231167420"
------=_Part_16_281734322.1528231167420
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit
Jenkins build failed: scf/PR-1576 on branch PR-1576 after 4.5 sec and counting
See logs on …
```
> Jenkinsfile: email notification on build failure

- bin/common/versions.sh
- bin/config-validator.rb
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
The new version no longer determines install/upgrade scenarios based on the absence or presence of kube objects, but uses the information from helm itself. It will always fail early if the previous secrets don't exist during an upgrade, and it will always delete any objects before creating them, so should never fail due to left-over objects from an earlier abandoned install.
> Bump scf-secrets-generator using HELM_IS_INSTALL property

- Makefile
- make/uaa-wait
The scripts are virtually identical, except wait-uaa has the namespace hardcoded in it. The Makefile already uses `make/wait uaa` in other places, so get rid of this duplication.
> Replace `make/uaa-wait` with `make/wait uaa`

- README.md
- bin/kube_overrides.rb
- make/tests
- src/scf-release/jobs/acceptance-tests/templates/run.erb
These changes make it easier to run a subset of :cat: in order to attempt to reproduce failures.
Usage:
`make/tests acceptance-tests env.CATS_SUITES="=v3" env.CATS_FOCUS="health"`
> Changes to make it easier to run a subset of 🐱

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
It is an alternative (and overrides) ROUTER_SSL_CERT (and KEY) and allows specification of multiple cert/key pairs.
> Add ROUTER_TLS_PEM structured property

- container-host-files/etc/scf/config/role-manifest.yml
This ends up generating resource requests for the static kube files,
which prevents them from running on Azure, etc. They can't be disabled
from a command line option like the helm charts can.
> Don't specify limits for tests

- Jenkinsfile
Note that https://github.com/SUSE/uaa-fissile-release/pull/112 is the real PR and this should point to UAA master again after it's merged.
> Set persistent storage class as default

- make/compile
Extend `grep` in `get_package_version_list` function of `make/compile` to exclude heading lines for Final and Dev releases. The change of the output was introduced by https://github.com/SUSE/fissile/pull/339.
Trying to keep the change as compact as possible, only the `grep` was modified. However, based on the output `fissile` generates, it could very well be that the `cut -d: -f1` part became obsolete.
> Fix get_package_version_list for Final releases

- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
This is required to avoid shell expansion of glob patterns, that would then collapse to nothing, for example in:
make/tests acceptance-tests-brain "env.INCLUDE=00[12]"
> Fix passing regex parameters for INCLUDE/EXCLUDE brain test options

- bin/config-validator.rb
- bin/vagrant-setup/common.rb
- container-host-files/etc/scf/config/role-manifest.yml
`env | grep CA_KEY` doesn't return the key in the pods anymore. My `api-0` didn't come up when testing this because monit wasn't running in the container but it could be a random (irrelevant) issue. Let's wait for CI to see if it is all green.
> Fix internal ca key exposed

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-garden-filesystem.sh
This is simpler for users and doesn't require a change when upgrading.
> Keep GARDEN_ROOTFS_DRIVER

- src/scf-release/packages/acceptance-tests-brain/packaging
Moving things around in the source directory can end up with files owned by root in unexpected places, causing issues when the user tries to delete those files later.  Instead, copy them to a temporary directory that is automatically deleted on container shutdown instead.
> acceptance-tests-brain: don't move things in ${BOSH_COMPILE_TARGET}

- bin/common/versions.sh
The CF CLI version here is almost 2 years old. There's several improvements around service brokers that are useful.
> Bump CF cli version

- container-host-files/etc/scf/config/role-manifest.yml
This should be related to the fact that BBS move to postgres
instead of etcd. Therefore the `must_be_odd` flag should not
longer apply to the `diego-api` role.
See https://docs.cloudfoundry.org/concepts/high-availability.html
> Refactor diego-api HA rules, odd value not required:

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/autoscaler-smoke/templates/run.erb
In the context of SCF (/other fissilized CF deployment), it is possible for the administrator to change the administrator password and then do something that requires the autoscaler to be restarted.  In that case the password embedded in the helm release will no longer be correct, which will cause the autoscaler to cease working.
Instead, use client credentials for the autoscaler (which would be generated anyway).  This ensures that we always have an auth method that will work even when the secrets are rotated.
This is independent of the autoscaler being used outside of SCF (where it might still be a good idea to use username / password authentication).
/cc @qibobo Could you see if this would make sense?  Longer term, we are planning on moving fissile to use BOSH ops files instead, in …
> autoscaler: Always use client_credentials

- bin/common/versions.sh
For some reason the openSUSE one was using `develop` builds instead of `release` builds; moved that back to match the SLE one.
> versions: bump fissile stemcell for configgin 0.16.2

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
This moves various ports around to avoid privileged ports, so that _most_ containers can avoid using privileged containers.  That is still needed for diego-cell and nfs-broker for non-port-related reasons.
Router SSL ports are not changed here pending upstream PR https://github.com/cloudfoundry/routing-release/pull/119
UAA does not appear to require PSP changes in my testing.
> Move ports around to avoid privileged ports

- container-host-files/etc/scf/config/role-manifest.yml
Because it's missing in that for some reason
> role-manifest: add `syslog_adapter` to syslog adapter cert

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
We just forgot to update the hard-coded BOSH property in the opinions that needs to list the CN of the cert
> role-manifest/opinions: Drop the syslog_adapter name again

- container-host-files/etc/scf/config/role-manifest.yml
Ref https://trello.com/c/8Af9uLyM/757-3-implement-ha-for-cc-clock-and-syslog-scheduler
:cat: results under vagrant:
1. 3x SA, both roles at count 1, as before the change. 3 fails.
1. 3x HA, both roles at count 2, now possible with the change. 4 fails.
SA:
```
3x  [Fail] [apps] Logging Syslog drains [It] forwards app messages to registered syslog drains 
1x  [Fail] [v3] v3 buildpack app lifecycle with a java_buildpack [It] can run spring apps 
```
HA:
```
3x  [Fail] [apps] Logging Syslog drains [It] forwards app messages to registered syslog drains 
1x  [Fail] [route_services] Route Services when a route binds to a service when service broker does not return a route service url [AfterEach] routes to an app 
2x  [Fail] [routing] Multiple App Ports [BeforeEach] when app has multiple ports …
```
> Allow HA (2 default/3 max) for roles cc-clock and syslog-scheduler.

- make/tests
- Allow namespace override
- Get better at finding the git root
- Support dist zip style helm layout
- Find configs from helm deployment instead of env files
This means we can now run this against a helm deployment of a release tarball.
> make/tests: various improvements

- make/tests
This is a fixup for https://github.com/SUSE/scf/pull/1695
> There is no y2j in the Vagrant box

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/idEoO8TD/765-expose-brokerclienttimeoutseconds
Ran tests under vagrant
- :green_heart: cluster build
- :green_heart: cluster start
- :green_heart: :smoking: 
- :green_heart: brain
- :boom: :cat: - Known thing for dev: `[Fail] [apps] Logging Syslog drains [It] forwards app messages to registered syslog drains`.
> Move `broker_client_timeout_seconds` setting out of opinions into an scf parameter.

- packer/Vagrantfile.template
When running `vagrant suspend`, it is much more useful to suspend to disk than suspend to RAM (because the latter doesn't free up any resources at all, making it kind of pointless).
This should be in vagrant-libvirt 0.0.32 and newer.
> vagrant: libvirt: suspend to disk

- make/tests
Not sure how useful this is going to be, given that the warning will be
quickly followed by multiple pages of debugging output, but I don't know
what else to do here; I didn't want to enforce a pause.
[trello#Op71whqm]
> Warn about HA UAA not supporting SSO lifecycle tests

- make/compile
This is a proposed alternative to #1700
> Allow the dev to disable the host compilation cache

- container-host-files/opt/scf/bin/pod-status
In newer versions of kubectl, pods from completed jobs show up too; we should mark them as successful.
> pod-status: mark completed pods as successful

- Jenkinsfile
This can happen on checkout failure, for example
> Jenkinsfile: don't upload logs if the log cleaner is missing

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/9EmTR4JL/775-3-add-psp-support-to-fissile-and-role-manifests
Ref: https://github.com/SUSE/fissile/wiki/Managing-Pod-Security-Policies
:warning: This is based on PR #1694 and cannot be merged before it.
> Add PSP declarations

- bin/dev/kube-ready-state-check.sh
We were explicitly checking that hyperkube is used, when sometimes the system may be running apiserver or kubelet (either as a stub for hyperkube, or as a standalone binary).  Fix our detection to support either (as long as we're still running the specific binary).
Fixes #1724.
> bin/dev/kube-ready-state-check.sh: support not using hyperkube

- .gitignore
- bin/dev/legalscan.sh
Submit OBS built buildpack dependencies for legal review. For the old buildpacks the sources are committed via Concourse which was not the case for the buildpacks built in obs.
> Submit obs buildpack dependencies for legal review

- Vagrantfile
- bin/common/versions.sh
- make/compile
Set FISSILE_COMPILATION_CACHE_CONFIG either directly to a JSON config or point it to a config file (inside the host, so for example `/home/vagrant/scf/output/package-cache.json`) to activate the new
caching code.
If the variable is not set, then the old caching code will still be used (for now).
> Add support for new fissile compilation cache

- make/tests
This is important now that Jenkins is using this script to run tests.
> Make sure make/tests returns with the test exit code

- container-host-files/opt/scf/bin/klog.sh
```
$ kubectl-1.9 get pods --output name --all-namespaces --show-all=true
pods/api-0
...
$ kubectl-1.10 get pods --output name --all-namespaces --show-all=true
pod/api-0
...
```
> Fix klog.sh for changed output from kubectl in 1.10

- Jenkinsfile
- container-host-files/etc/scf/config/role-manifest.yml
- make/tests
- src/scf-release/jobs/acceptance-tests-brain/spec
- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
- src/scf-release/packages/acceptance-tests-brain/packaging
- src/scf-release/packages/acceptance-tests-brain/spec
- src/scf-release/packages/credhub-cli/packaging
- src/scf-release/packages/credhub-cli/spec
- src/scf-release/packages/mariadb-client/packaging
- src/scf-release/packages/mariadb-client/spec
- src/scf-release/src/acceptance-tests-brain/test-scripts/004_tcprouting_test.sh
- src/scf-release/src/acceptance-tests-brain/test-scripts/007_buildpacks_test.sh
- src/scf-release/src/acceptance-tests-brain/test-scripts/008_cf_usb_test.sh
- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.sh
- src/scf-release/src/acceptance-tests-brain/test-scripts/013_credhub_test.sh
Ref: https://trello.com/c/T7m367ac/814-3-create-brain-test-for-credhub
Testing under vagrant passes.
Two semi-related changes:
- Use apply in `make/tests` now. `create` will error for pre-existing CR, CRB from previous test runs. `apply` either ignores or overwrites them (with the same).
- Small typo in tmp dir name for 011 test.
> Create brain test for credhub

- container-host-files/etc/scf/config/role-manifest.yml
Hello,
This should cover the item https://www.pivotaltracker.com/story/show/160013733
Basically this includes:
- Moving the `loggregator-agent` as an `instance_group` of the type `colocated-container`
- Remove the `loggregator_agent` as an item of the `jobs` for all `instance_groups` using it, and replace it with the `properties.bosh_containerization.colocated_containers["loggregator-agent"]`
worked together with @HeavyWombat
> configure metron-agent as a colocated-container

- bin/config-validator.rb
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
The script sets `KUBE_NATS_CLUSTER_IPS`. `KUBE_MYSQL_CLUSTER_IPS`, and `KUBE_CONSUL_CLUSTER_IPS`, but only the first one is still being used.
The validator was also checking for `KUBERNETES_CLUSTER_DOMAIN`, but that one isn't being set by this script, it is set by run.sh in the fissile stemcell.
The only remaining properties that require the script are:
```
diego.route_emitter.nats.machines: ((KUBE_NATS_CLUSTER_IPS))((#KUBE_SIZING_NATS_COUNT))((/KUBE_SIZING_NATS_COUNT))
nats.machines: ((KUBE_NATS_CLUSTER_IPS))((#KUBE_SIZING_NATS_COUNT))((/KUBE_SIZING_NATS_COUNT))
```
In addition to the obvious suspects, this is being used by all roles that use the route_registrar.
> Remove configure-HA-hosts.sh from roles that don't need it

- container-host-files/etc/scf/config/role-manifest.yml
On some kube systems hairpin connections (going to the same container via the service) is not supported; as the operator connects to the scheduler and the scalingengine this can be problematic.  Move it to a new role that has nothing else to work around the issue.
The servicebroker also must not be co-located with apiserver.
The eventgenerator cannot be co-located with metricscollector.
@qibobo I'm picking where to put the jobs more-or-less randomly; please let me know if there are better choices. Unfortunately GitHub doesn't want to let me pick you as a reviewer…
> autoscaler: move operator to new role

- Jenkinsfile
- Vagrantfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/cc_pre_start_home.sh
- make/run
- make/upgrade
- packer/Makefile
- packer/http/add-github-users.sh
- packer/http/apiserver-vagrant-overrides.env
- packer/http/controller-manager-vagrant-overrides.conf
- packer/http/create-kubelet-overrides.sh
- packer/http/docker.conf
- packer/http/install-jenkins-slave.sh
- packer/http/kubelet-vagrant-overrides.conf
- packer/http/kubelet-vagrant-overrides.env
- packer/http/make-var-run-kubernetes.service
- packer/http/setup-data-partition.sh
- packer/scripts/install-certstrap.sh
- packer/scripts/install-kubernetes.sh
- packer/scripts/install-slave-tools.sh
- packer/scripts/setup-pod-security-policies.sh
- packer/vagrant-box.json
This bumps the Jenkins slave (as an AMI) to kube 1.10.
Includes a workaround for the thing where we need `CAP_SYS_RESOURCE` for a few roles that run `ulimit -n` in their init scripts; we still need a better fix there.  Note also that the new kube supports PSPs (so the scripts are updated to account for it).
Please see the individual commit messages for details.
Resolves #1847
> Upgrade Jenkins slave (on AWS) to kube 1.10

- container-host-files/etc/scf/config/scripts/forward_logfiles.sh
`monit` is normally not in the `$PATH` since it was moved into a (BOSH) package; refer to it by the explicit path to ensure that we can find it.
> forward_logfiles: use explicit path to monit

- Vagrantfile
This passes through `/dev/random` to the VM to hopefully let it get more entropy.
Documentation on the argument: https://github.com/vagrant-libvirt/vagrant-libvirt#random-number-generator-passthrough
> vagrantfile: libvirt: passthrough random

- container-host-files/etc/scf/config/role-manifest.yml
This fixes the external URL for cf-usb such that it's consistent from SCF < 2.14.
For upgrades from 2.14 the [release notes from CAP 1.3 (=SCF 2.14.5)][1] will have to be followed in reverse.
[1]: https://github.com/SUSE/cap-release-notes/blob/master/adoc/Release-Notes.adoc#release-13-november-2018
> role-manifest: cf-usb: don't use job name in service name

- bin/common/versions.sh
- make/kube
This will need to be (possibly pre-emptively) bumped for a CAP release; it is basically irrelevant for SCF.
> helm: add product version field as `appVersion`

- bin/fissile
Since `set -o errexit` was set, we don't need `exit 1` in the case where `mktemp` fails.
> Removed unnecessary exit 1

- container-host-files/etc/scf/config/opinions-common.yml
With the move from `metron agent` to `loggregator agent`, the setting
for the deployment name changed from being under `metron_agent` to be
under the main properties section. Configuration for the setting in
the spec file: https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/jobs/loggregator_agent/spec#L37
Compare with https://github.com/cloudfoundry/cf-deployment/blob/38b304405764e1307f606d02856e4366b2337cbd/operations/community/change-metron-agent-deployment.yml
which shows the change in an operations file.
Without this change, the event envelope of the loggregator agent will
have an empty value for the deployment name and this might cause
consumers to bail out with a malformed envelope error.
Run `cf nozzle` to check whether a deployment name is set or not:
``` …
```
> Move deployment name to properties section

- container-host-files/etc/scf/config/role-manifest.yml
The predefined podAntiAffinity rule does have an outdated component name (api), causing the matchExpression to be invalid.
Previously the api-group was named api, hence the values filter did still work.
https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/role-manifest.yml#L648
> matchExpression has to match component name (api-group)

- README.md
This change re-orders the execution commands for acceptance tests listed in README. Since `cats` test might be destructive, therefore must be run in the end. Also, adding scalar-smoke test.
> Updated execution order for acceptance tests

- Jenkinsfile
- make/bundle-dist
- make/kube-dist
Helm can't install tgz charts if there are directories in the archive. This also means we can go back to uploading zip files for the release tool, since that needs to be manually extracted anyway.
> Dist: upload helm charts without separately

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_gorouter_bpm_dns.sh
- container-host-files/etc/scf/config/scripts/patches/fix_route_registrar_bpm_dns.sh
- container-host-files/etc/scf/config/scripts/patches/fix_routingapi_bpm_dns.sh
- Remove various superfluous quotes in yaml values.
- Bump the CF_VERSION reported by scf.
- Added comments to the bpm patch scripts explaining our need for 'unsafe.unrestricted_volumes'.
See https://github.com/SUSE/scf/pull/1921 for the origin of the comments fixed here.
Ref https://trello.com/c/wqcKOPJC/895-cf-bump-part-1-cf-v36
> Follow up on CF Bump to 3.6.0. Addressing remaining comments.

- container-host-files/etc/scf/config/opinions-common.yml
Changes the URLs for the v3 API to use HTTPS instead of HTTP.
Calling `cf curl /v3` shall report the URLs as HTTPS instead of HTTP.
Fixes #1900
> v3 API use HTTPS instead of HTTP

- container-host-files/opt/scf/bin/klog.sh
This PR contains the following changes [(Trello Task)](https://trello.com/c/4KTbZVtU/901-2-klogsh-needs-to-be-updated-to-supported-multiple-containers-per-pod):
1. Updating `kubectl` commands 
2. Adding support for fetching kube logs from multi-container pods
2. Code Refactoring
> Refactored klog.sh and added support for multi-container pods

- README.md
Ref: https://trello.com/c/Vr7di1lY/875-make-app-domains-configurable
Also: https://github.com/SUSE/scf/wiki/How-To-Customize-the-Application-Domains
> Document how to customize the application domain in CAP (1.3.1 or higher, not 1.3).

- .envrc
- .gitignore
- bin/fissile
- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://trello.com/c/W0YvSEfG/917-2-add-back-defaultstack-setting
- Removed the associated properties from the opinions.
- Role manifest
- Restored the DEFAULT_STACK parameter exposing this setting.
- Restored the property assignments using this parameter.
- Modified the fissile wrapper script to assemble a role manifest like
it does for the light opinions. This brings in the proper
`the-stack-name` which got selected via USE_SLE_BASE, and makes it
referable from the `default` key of the `DEFAULT_STACK`
parameter. We use the same stack-specific part files as for the
light opinions.
Note: The new final role manifest is a sibling of the original role
manifest which is now serving as parts. Needed to not break the
script paths.
- This way of handling the changed default value for …
> Restoring DEFAULT_STACK to users.

- .envrc
- bin/common/versions.sh
You can now customize the cache location for downloaded final releases in fissile, and the default location has changed to `~/.final-releases`. Under Vagrant this is not part of the shared host folder, so would be lost every time the box is recreated.
> Set fissile --final-releases-dir to the heritage location

- container-host-files/etc/scf/config/role-manifest.yml
These instance groups include scripts which attempt to set `ulimit -n`, which requires `SYS_RESOURCE` to do.
> role manifest: ask for SYS_RESOURCE caps where necessary

- Vagrantfile
Allows customization of the Vagrant machine.
- Create a directory somewhere outside the repo.
- Create a `provision.d/` directory under it.
- Add some custom scripts to `provision.d/`. E.g.
```
#!/bin/sh
zypper install -y vim
```
- Start Vagrant with `SCF_VM_CUSTOM_SETUP_SCRIPTS=<directory_containing_the_provision.d> vagrant up`
- Check that vim was installed inside the Vagrant machine.
> Customization of Vagrant box with provided scripts

- container-host-files/etc/scf/config/role-manifest.yml
- for the `diego-cell` ig, the healthcheck command was lacking of a
parent key, which should be `readiness`, based on the struct
define in fissile(see [fissile code](https://github.com/cloudfoundry-incubator/fissile/blob/develop/model/role_run.go#L99-L116))
- key `exposed-ports` is obsolete
- the value for a variable under the `default` key, produce errors when
unmarshalling the YAML, e.g. `yaml: unknown anchor 'the-stack-name' referenced`,   therefore I considered that this value should be quoted.
Opinions?
> Some paths inside the role-manifest.yml are not correct

- container-host-files/etc/scf/config/role-manifest.yml
Turns out we didn't actually _have_ a probe script; it previously worked because the role manifest had an error and the readiness probe was never used.  Now that we fixed the typo, we try to make it use a non-existent readiness probe instead, which always fails.
See also #2015 (merged in 04f0c59c6d55151d2a440c11e9508d16f424d668) where we merged the typo fix (and broke the build).
See also https://github.com/SUSE/scf-helper-release/tree/master/jobs/global-properties/templates where there is no `diego-cell` readiness probe.
> Role manifest: Remove diego-cell readiness probe

- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.sh
The minibroker charts changed how the images are fetched; fix up the test scripts so we can find them again (by overriding the appropriate bits in the helm values).
Also, dump out relevant information when tests fail.
> acceptance-tests-brain: 012_minibroker_redis: fix image pulling

- Vagrantfile
Loads the loop kernel module on system startup, as well as during the Vagrant machine provisioning.
It prevents diego-cell-0 from crashing for the first time it tries to perform a mount using a file as a filesystem.
> Added provisioning for loading the loop kernel module

- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
- src/scf-release/packages/helm/packaging
Ref https://trello.com/c/ZLlm1pbe/933-minibroker-brain-test-for-redis-fails-due-to-client-mismatch
Package all versions needed by vagrant, our CI, an CaaSP3.
Detect and choose version to use at runtime (brain tests).
> Support multiple versions of the helm client

- Vagrantfile
- packer/.gitignore
- packer/http/apiserver-vagrant-overrides.env
- packer/vagrant-box.json
- Added the default admission plugins (the ones when `--enable-admission-plugins` is not set).
- Kept `PodSecurityPolicy`.
- Added `MutatingAdmissionWebhook` and `ValidatingAdmissionWebhook` as requested for Istio automatic sidecar injection (https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection).
- Added `KUBE_API_ARGS` with its default value and appended `--runtime-config=admissionregistration.k8s.io/v1alpha1` to it to get `admissionregistration.k8s.io/v1alpha1` enabled, also a requirement for Istio automatic sidecar injection.
- On a current running Vagrant machine, replace the contents of `/etc/systemd/system/kube-apiserver.service.d/vagrant-overrides.env` by the ones in this PR.
- Restart the `kube-apiserver`: `sudo systemctl restart kube-apiserver`.
- …
> Enable extra admission plugins on k8s inside Vagrant

- container-host-files/etc/scf/config/role-manifest.yml
The `name` and `version` keys are currently not used by fissile; those values are extracted from `release.MF` for final releases. The values should at least be validated though, but for now this commit just fixes the names of the buildpack releases.
> Fix names for buildpack releases

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/check_swapaccounting.sh
Added a pre-start check to Diego cell for swap accounting.
If swap accounting is not enabled, it prints a red message to the stderr and exits with 1.
The logic is simple, disable swap accounting on the machine you are going to perform the test and deploy CAP. Diego cell should never come up.
On a Vagrant machine this can be done through the following:
1. `sudo vim /etc/default/grub`, then remove `swapaccount=1` from `GRUB_CMDLINE_LINUX_DEFAULT`.
2. `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`.
3. From the host, run `vagrant reload`.
4. `vagrant ssh` back and watch for the Diego cell pod.
5. Check the logs with `kubectl logs --follow --namespace cf diego-cell-0 -c diego-cell`.
6. Put `swapaccount=1` back to the grub kernel boot parameters and reboot with `vagrant reload`.
7. Check that …
> Pre-start check on Diego cell for swap accounting

- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
- src/scf-release/packages/helm/packaging
**For brain tests**
Perform a check whether the helm client matches the server version. If not, download the version to match the server.
Get a Tiller version different than 2.11.0 deployed to a supported k8s cluster and run a minibroker brain test.
> Brain tests - match the helm client according to the server version

- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
If we find no pods, then assume the pods just haven't been created yet, and don't finish the wait loop.
> acceptance-tests-brain: helpers: don't accept podless namespace as ready

- container-host-files/etc/scf/config/role-manifest.yml
The ports go via the gorouter anyway; don't mark them as public so that things work correctly behind load balancers.
Testing this in a PR to free up local resources; this has not been previously tested and shouldn't even be reviewed until the autoscaler smoke test passes in CI.
> autoscaler: don't mark ports as public

- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.rb
When errors happen, we should provide more information on what is failing; currently it's just a very uninformative message.
> acceptance-tests-brain: minibroker/redis: be more verbose

- chart-parts/ingress.yaml
- Adds missing NGINX Ingress Controller annotations.
- Changes the name of the resources to more meaningful ones (not tied to a specific Ingress Controller).
- Injects the backend port.
- Deploy the NGINX Ingress Controller.
- Deploy SCF with the below additional values and no `kube.external_ips`:
```
services:
ingress:
class: nginx
backends:
router:
port: 443
```
- Check GoRouter can be reached through the Ingress Controller.
> Ingress resource - add necessary annotations and small refactors

- Vagrantfile
- packer/http/controller-manager-vagrant-overrides.conf
- packer/vagrant-box.json
The `After=` line goes in the `[Unit]` section, not the `[Service]` section.
> packer: fix kube-controller-manager systemd unit

- bin/common/versions.sh
- src/scf-release/config/blobs.yml
- src/scf-release/packages/cli/spec
It appears that nothing major has changed (for our purposes), and the tests continue passing.
> scf-release: Bump CF CLI version to 6.42.0

- bin/common/versions.sh
Note that it was previously mistakenly set to 1.13.1 when it should have been 1.3.1
> versions: Bump to 1.3.2

- make/include/defaults
- make/include/wait_for
- make/ingress/update_secrets
- Switch from `stable/nginx-ingress` to `suse/nginx-ingress`.
- Fix to the function that waits for a job.
Deploy SCF with NGINX Ingress Controller:
```
(export INGRESS_CONTROLLER=nginx; make run)
```
Upgrade SCF to add the missing bits:
```
(export INGRESS_CONTROLLER=nginx; export SCF_ENABLE_AUTOSCALER=true; export SCF_ENABLE_CREDHUB=true; make upgrade)
```
Run CATS.
> SUSE nginx-ingress

- bin/common/versions.sh
We need ruby 2.4.0 for SLE stemcell to work correctly
> versions: bump stemcell

- src/scf-release/src/acceptance-tests-brain/test-scripts/016_minibroker_mongodb_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/016_minibroker_mongodb_test_disabled.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Service creation and deletion are async and requires proper waiting.
Also, disabling the mongodb brain test temporarily.
Brain tests should pass.
> Added wait funcion for async service operations on brain tests and disable mongodb test temporarily

- src/scf-release/src/acceptance-tests-brain/test-scripts/017_syslog_forwarding_test.rb
Semi-passed Jenkins: The test 017 changed here passed. The unchanged minibroker mongodb test failed. See https://github.com/SUSE/scf/pull/2146 for the PR disabling that test.
> Fix missing `socat` under SLE

- make/ingress/nginx/run
- make/run
- make/upgrade
Updated the make scripts to deploy SCF with `UAA_PORT=443` when the Ingress Controller is enabled.
This PR also bumps the uaa-fissile-release that introduces the possibility to specify `UAA_PUBLIC_PORT`.
- Deploy SCF with Ingress Controller set to `nginx`.
- Verify that the port 2793 is not in the NGINX Ingress Controller passthrough.
- Run the tests.
> UAA through ingress controller

- chart-parts/ingress.yaml
- container-host-files/etc/scf/config/opinions-common.yml
- container-host-files/etc/scf/config/role-manifest.yml
- make/ingress/nginx/run
Switch from port 4443 to port 443 (which is the default value) for doppler. GoRouter handles both https and wss on port 443 by default.
This PR also removes the TCP passthrough from the NGINX Ingress Controller make scripts that deploy it to Vagrant, making the WebSocket connection to go through the Ingress Controller when it is enabled.
- CI should pass with the current configuration (no Ingress Controller enabled).
- On a Vagrant machine, deploy SCF with `(export INGRESS_CONTROLLER=nginx; make run)`.
- Run the tests related to logging, which should use doppler to consume them.
> Handle WebSockets in the ingress controller

- src/scf-release/src/acceptance-tests-brain/test-scripts/009_backup_test.rb
There is no need for `sleep 60` after running `cf backup restore` as it is not an async operation.
(Also fixing punctuation)
Brain tests should pass.
> Brain test - backup and restore without sleep

- container-host-files/etc/scf/config/role-manifest.yml
Use port 9024 instead of 9022 on CC for mutual TLS with GoRouter.
Reference https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.66.0#p%3dcc.public_tls
Deploy SCF and perform an operation with the cf CLI. Then get a shell session to the `router-0` and `cat /var/vcap/sys/log/gorouter/access.log`. It shall show it is using port 9024. E.g.:
```
api.cf-dev.io - [2019-03-05T03:33:33.282+0000] "GET /v2/jobs/... HTTP/1.1" 200 0 270 "-" "go-cli 6.40.0+07673feb9.2018-10-08 / linux" "172.16.0.1:56432" "172.16.1.182:9024" x_forwarded_for:"172.16.0.1" x_forwarded_proto:"https" vcap_request_id:"..." response_time:0.01207756 app_id:"-" app_index:"-"
```
> Enable mutual TLS between Cloud Controller and GoRouter

- Jenkinsfile
- container-host-files/opt/scf/bin/klog.sh
- Modified `Jenkinsfile` to execute the `klog.sh` script
- Modified `s3` bucket path to accommodate `klogs`
- Modified `klog.sh` to support args from Jenkins
- Introduce failures in tests and trigger build
- Check whether `klog.sh` was triggered even if the build failed
- Verify if both build logs and klogs were dumped in correct s3 buckets
e.g: `https://s3.console.aws.amazon.com/s3/buckets/cap-jenkins-log/prs/PR-2170-jenkins-scf-PR-2170-6/`
> Jenkins: Grab and dump logs to s3 on failed runs

- make/tests
- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
- Update the submodule testbrain.
- Remove the default `--verbose` from the brain run template.
- Add a `VERBOSE` env var to handle verbosity.
- Small fixes to `make/tests` script.
- Run a specific test without passing `env.VERBOSE`:
`make/tests acceptance-tests-brain env.INCLUDE="cflogin"`
- It should not print the stdout and stderr from the test, but should show which test was run and if it passed or not.
- Run a specific test passing `env.VERBOSE`:
`make/tests acceptance-tests-brain env.INCLUDE="cflogin" env.VERBOSE="true"`
- It should stream the stdout and stderr from the test.
- Run a specific test WITHOUT passing `env.VERBOSE` again, but before, make a change to the test so it fails.
- It should dump the output at the end of the test run.
> Brain test runner - stream test output when --verbose is set

- src/scf-release/packages/kubectl/packaging
- src/scf-release/src/acceptance-tests-brain/test-scripts/013_credhub_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Updates the `testbrain` and skips credhub test if credhub is not enabled. Also, updates the kubectl version.
Run credhub brain test without having it enabled. It should be skipped.
> Update testbrain to allow skipping tests and skip credhub test

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/set_vcap_limits.sh
This PR resolves https://github.com/SUSE/scf/issues/2100.
It enables changing the hard and soft limits for the max processes for the vcap user inside the container for each role.
They can be set by passing the `env.VCAP_HARD_NPROC` and `env.VCAP_SOFT_NPROC`  values during deployment.
- Deploy SCF without specifying `VCAP_HARD_NPROC` and `VCAP_SOFT_NPROC`, and:
- Get a shell session to any container and:
- `su vcap`
- `ulimit -u` -> should return 4096 (the default value).
- Perform an upgrade setting only `VCAP_HARD_NPROC`:
- The containers should error. Grab the logs of the failed container with `kubectl logs -n cf diego-cell-0 -c diego-cell -p`. The error should say `VCAP_SOFT_NPROC must be set when VCAP_HARD_NPROC is set`.
- Repeat the previous point, but setting only `VCAP_SOFT_NPROC`. …
> Set vcap hard and soft nproc limits for every role

- bin/common/versions.sh
Ref https://trello.com/c/H2AXtiHz/974-packages-mv-should-happen-at-build-time
Fissile PR brought in here: https://github.com/cloudfoundry-incubator/fissile/pull/477
> Replace combination of build-time symlinks and runtime moves with build time moves.

- make/tar-sources
Sources hashes now are also part of .MF file,
so we need to parse them in order to extract the stage, that
we later use to compose the package name which is submitted to OBS.
Signed-off-by: Ettore Di Giacinto <edigiacinto@suse.com>
> Fix broken manifest parsing

- README.md
- Vagrantfile
- make/deploy-mysql
- packer/http/docker.conf
- packer/scripts/create-kube-certs.sh
- src/scf-release/src/acceptance-tests-brain/test-resources/nfs_mount.json
- src/scf-release/src/acceptance-tests-brain/test-resources/nfs_secgroup.json
The A record for cf-dev.io changed from 192.168.77.77 to 192.168.47.109. This PR minimizes the impact of subsequent changes to the records of cf-dev.io.
Vagrant should work again with cf-dev.io without any problems, as well as the updates to docs should work as expected.
> Fix the IP address cf-dev.io A record resolves to

- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Credhub brain test was being skipped on CI due to output discrepancy from kubectl versions used on Vagrant for development and on CI.
The fix uses kubectl `--output go-template=` to accomplish portability.
Credhub brain test should not be skipped on CI.
> Fix for credhub brain test being skipped on CI

- container-host-files/etc/scf/config/role-manifest.yml
This PR is to address the bumping of `CF` from version `6.4` to `6.6`. Here are the changes to individual modules:
```
cf-cli,1.10.0 -> 1.11.0
cf-smoke-tests,40.0.20 -> 40.0.20
credhub-release,2.1.1 -> 2.1.2
diego-release,2.23.0 -> 2.24.0
loggregator-release,104.1 -> 104.4
routing-release,0.183.0 -> 0.184.0
```
```
uaa-fissile-release,66.0 -> 67.0
cf-acceptance-tests-release -> https://github.com/cloudfoundry/cf-acceptance-tests/tree/ef3230ea83718be88c99bfea372936aeb0bcb573
```
**Details:** https://trello.com/c/D2SjQJMP/970-cf-bump-part-3-610
> CF Bump to v6.6

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
If the namespace doesn't exist, it prints an error before creating a new namespace. It is not the desired behavior.
`Error from server (NotFound): namespaces "minibroker-..." not found` should not be shown.
> Brains minibroker - remove confusing output

- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/014_minibroker_mariadb_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/015_minibroker_postgres_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/016_minibroker_mongodb_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
Minibroker tests are failing on nightly CI runs.
https://ci.howdoi.website/teams/main/pipelines/Nightly-cap-qa-deployment-NoCats-develop/jobs/Nightly-cap-qa-deployment-NoCats-develop-SA/builds/2
This PR attempts to solve the issues by:
- Raising the number of retries before timing out on the wait on service creation.
- Performing a `cf restage` after binding the service to the app.
- Adding `-L` to follow any redirection the `curl` assertions shall perform.
Jenkins CI should pass, as well as the Concourse CI that performs the nightly builds.
> Brains - minibroker nightly fails

- container-host-files/etc/scf/config/role-manifest.yml
This fixes issues with our current cf-acceptance tests.
This reverts commit b248af2361fa02272d0bdafeec6302622cf6793c.
> Revert "Bump go-buildpack release to 1.8.36.1"

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
This PR is to address the bumping of `CF` from version `6.6` to `6.10`. Here are the changes to individual modules:
```
cf-mysql-release,36.16.0 -> 36.17.0
cf-smoke-tests-release,40.0.42 -> 40.0.44
diego-release,2.24.0 -> 2.25.0
garden-runc-release,1.17.1 -> 1.17.2
```
```
uaa-fissile-release,67.0 -> 68.0
cf-acceptance-tests -> 
```
**Details:** https://trello.com/c/D2SjQJMP/970-cf-bump-part-3-610
> CF Bump 6.10

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
When a run fails, print out logs of the minibroker & -pods containers, in case they contain information that can help us figure out what went wrong.
> brains: minibroker: emit logs on failure

- bin/common/versions.sh
Ref https://trello.com/c/XvU6E5Vg/955-allow-bumping-up-the-nproc-limit-for-vcap-user
Bump fissile to proper develop version.
> Alternate implementation of nproc limits, via fissile

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_postgres_prestart.sh
This PR ensure that authorize-internal-ca runs as a second job right after the global-properties.
This relies on the ordering being preserved when passed to Fissile.
https://github.com/cloudfoundry-incubator/fissile/pull/485 ensures the order of execution of pre-start scripts is preserved.
Blocked by https://github.com/cloudfoundry-incubator/fissile/pull/485.
>  Ensure authorize-internal-ca as a second job in the list

- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Ref: https://trello.com/c/UL1n6gO0/1007-nfs-persi-brain-failing-on-nightly-caasp3
Extended narrative tracing around the startup of the nfs-test-server pod.
> Brain test NFS persi - Get more information out of it

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
If we could not get the logs out of a container for some reason when logging failures (e.g. ContainerCreating), describe the pod so that we might have a chance to diagnose the error.
In rare cases (less rare on terrible hardware), we can end up with the test failing while the pod isn't ready (e.g. because it hasn't managed to pull the image yet).  When we try to get the logs, it could give us useless errors:
> Error from server (BadRequest): container "mariadb" in pod "erstwhile-squid-mariadb-slave-0" is waiting to start: PodInitializing
In this case, try running a `kubectl describe`, in the hopes that we will get the relevant event logs to help us troubleshoot the problem.
1. Run the minibroker brain tests on a really slow machine
> brains: minibroker: if failing to show logs, show the pod

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
- Force the Minibroker image to be downloaded, even if the tag `latest` is already cached (it may have changed).
- Wait for the underlying Minibroker resources to be ready.
Brain tests should pass on Jenkins and Concourse.
> Wait for Minibroker service resources

- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.rb
From the nightly fail on the Redis test, it is not clear what failed in the app that uses the provisioned Redis.
> Brains Redis - add --fail to the curl assertions

- make/run
- make/upgrade
- src/scf-release/src/acceptance-tests-brain/test-resources/docker-uploader/manifest.yml
- src/scf-release/src/acceptance-tests-brain/test-scripts/010_insecure_registry_test.rb
We were incorrectly using `CF_DOMAIN` for the TCP route, which does not work on actual cloud deployments where the TCP port is on a different load balancer / IP address than the router.
> brains/010-insecure-registry: use TCP domain for TCP route

- src/scf-release/src/acceptance-tests-brain/test-resources/nfs_server_kube.yaml
https://trello.com/c/UL1n6gO0/1007-nfs-persi-brain-failing-on-nightly-caasp3
Apparently ECP CaaSP3 does not have enough disk to satisfy the test server's request.
As really do not need that much, reduced the claim to improve chances of having it satisfied.
Pass the jenkins CI.
Pass the ECP CaaSP3 CI.
> Reduce disk used by nfs testing

- make/tests
Sometimes logs are missed between the `kubectl logs` and `kubectl attach`. The changes here make the logs to start to be streamed much quicker.
> Start streaming logs faster for test containers

- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/012_minibroker_redis_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/014_minibroker_mariadb_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/015_minibroker_postgres_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/016_minibroker_mongodb_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Use `KUBERNETES_STORAGE_CLASS_PERSISTENT` environment variable on all brain tests that rely on storage classes.
Should pass Jenkins and Concourse on the various platforms we test.
> Brain tests - use KUBERNETES_STORAGE_CLASS_PERSISTENT as storage class

- Jenkinsfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- make/run
- make/run-eirini
- make/upgrade
- make/upgrade-eirini
Reverts SUSE/scf#2278
Reverting the revert. For more details, revert the explanation on the revert, and the reason for this revert will be unveiled.
After a team discussion, the feature flags is ready to be used as designed.
> Revert "Revert "Use feature flags for autoscaler, cf_usb, credhub, eirini""

- src/scf-release/src/acceptance-tests-brain/test-scripts/015_minibroker_postgres_test.rb
Removed unnecessary calls on the Minibroker Postgres brain test, as well as added a missing `--fail` to the `/todos` call.
Should pass CI.
> Minibroker Postgres brain test assertion cleanup

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
Rely on Helm's `--wait` for the Minibroker installation on the brain test.
Brain tests should pass on CI.
> Brain Minibroker install rely on Helm --wait

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
The Minibroker related namespace deletion can happen on the background. In some cases, waiting for the namespace to be deleted can cause the tests to timeout.
Brain tests should pass on CI.
> Brain tests - don't wait for namespace deletion

- bin/dev/kube-ready-state-check.sh
`swapaccount=1` on the `/proc/cmdline` is not a definitive check for swap being accounted. According to https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt, section 2.4:
```
When swap is accounted, following files are added.
- memory.memsw.usage_in_bytes.
- memory.memsw.limit_in_bytes.
```
This refactor makes the check portable. E.g. on Minikube swap is accounted, but no `swapaccount` is passed to the boot parameters.
Run the script on a system with accounted swap disabled, then run on a system with accounted swap enabled.
> Portable accounted swap check on kube-ready-state-check.sh

- bin/common/versions.sh
Ref: https://trello.com/c/Zq4jVCv8/1022-14rc1-wrong-app-version-132
Fixes the bug where our charts shows 1.3.2 as app version instead of 1.4
Build the charts from the branch, then check the `appVersion` in `Chart.yaml`.
> Bump product version.

- Jenkinsfile
Left over? SATS is not used to reference BRAIN tests.
> SATS -> BRAIN on Jenkinsfile

- src/scf-release/src/acceptance-tests-brain/test-scripts/011_nfspersi_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
This adds a helper function to trigger an exception some amount of time before the (expected) runner-triggered abort happens.  Ideally this should mean we do better at cleaning up any resources we create.
Run the NFS-persi tests somewhere slow.
Actually, I locally modified `000_cflogin_test.rb` to fail in the correct way (by making the timeout 10 seconds, and adding a 10 second sleep):
```
use_global_timeout
puts "Current time is #{DateTime.now.rfc3339}"
at_exit { puts "Exiting at #{DateTime.now.rfc3339}" }
puts "Starting to sleep at #{DateTime.now.rfc3339}"
sleep 10
```
Output:
```
FAILED: 000_cflogin_test.rb
Test output:
…
Current time is 2019-04-10T22:12:04+00:00
…
Starting to sleep at 2019-04-10T22:12:05+00:00
…
/var/vcap/packages/acceptance-tests-brain/test-scripts/000_cflogin_test.rb …
```
> brains: add global timeout

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
This is to implement restarting dependent pods on exported BOSH property change.
See also:
https://github.com/cloudfoundry-incubator/configgin/pull/97
https://github.com/cloudfoundry-incubator/fissile/pull/470
https://github.com/SUSE/uaa-fissile-release/pull/153
1. Deploy SCF
2. Upgrade with `make/upgrade --values /dev/shm/foo.yaml` where the YAML file has:
```yaml
bosh:
instance_groups:
- name: doppler
jobs:
- name: doppler
properties:
doppler:
grpc_port: 8081
```
3. Manually delete the `doppler` pod. (The `doppler` that comes up will be broken, that's okay)
4. Check that `log-api` restarted on its own.
> role-manifest: allow configgin-roles to patch statefulsets

- src/scf-release/src/acceptance-tests-brain/test-scripts/016_minibroker_mongodb_test.rb
On slow clusters, we could take too long to deploy the mongo pod; if kube happens to kill the pod at a bad time, we could end up with an unrecoverable state.
The proper fix is to change the mongodb helm chart to use an init container, instead of just running the initial db setup in a script.
This also enables extra logging, in case that helps.
The acceptance-tests-brain test `016_minibroker_mongodb_test` should be run a very slow cluster.
> brains/minibroker-mongo: disable pod liveness probe

- container-host-files/etc/scf/config/role-manifest.yml
We need to be checking the health check port for bbs, instead of the actual listen port (which wouldn't be active when we don't have the lock).
1. Deploy SCF with >1 diego-api instances
2. See that both are Ready
> role-manifest: fix diego-api readiness probe

- container-host-files/etc/scf/config/role-manifest.yml
App Autoscaler Postgres instance doesn't need 100 GB. Reducing it to 5.
> Reduced Autoscaler database disk size

- .envrc
- .gitmodules
- Makefile
- container-host-files/etc/scf/config/role-manifest.yml
Consumes https://github.com/cloudfoundry-community/eirini-bosh-release and remove the eirini submodule. Tested locally with my vagrant box and I can push apps and access them as usual. After merging this, automation will take care of bumps
- make vagrant-prep
- make run-eirini
- .... see if eirini is up, push an app and see if works
> Remove Eirini release as submodule (and use a final release instead)

- bin/dev/kube-ready-state-check.sh
This addresses the following issues (esp. when run in the pipeline):
- auth test will fail for nonauth, and log respectively (currently the first test just failed for noauth, saying you need to have 4/4 kube-dns pods)
- remove explicit pod numbers from status messages, as 1. they were wrong, 2. we don't check for a pod number, but only if requested ones are ready - therefore "N/N"
- storage class test passed, when kube couldn't authenticate - now fails here as well
run "./kube-ready-state-check.sh kube" (didn't verified for e.g. AWS/EKS)
> Fix kube ready state check

- container-host-files/opt/scf/bin/klog.sh
Ref: https://trello.com/c/omFBqdlS/1031-klogsh-should-not-error-out-when-containers-are-not-running
Moved all kube operations into functions with nice names.
Prevent abort when retrieving kube logs (`|| true`)
Added narrative output, let users see the script working instead of waiting a few minutes with no indication of operation.
Note: Hoisted determination of pod phase out of container loop, need this only per pod, not per container.
- Start a cluster where one or more pods are CrashLoopBackOff, or not fully started.
- Run klog.sh against the cluster.
- See it complete instead of aborting on the bad pods.
> Reworked klog to continue on bad pods, containers.

- Jenkinsfile
Execute `kubectl get all --namespace {cf,uaa} --output wide` for a better insight of what was going on on the k8s side of things when tests fail.
Fail a Jenkins test (should happen as of now).
> Improve Jenkins log on failure

- chart-parts/ingress.yaml
According to https://helm.sh/docs/chart_best_practices/#standard-labels, it is recommended to label the objects with the Helm related labels.
Dependent on:
https://github.com/SUSE/uaa-fissile-release/pull/154
The labels should be applied correctly, similar to the rest of the CF roles.
> Add Helm labels to ingress templates

- README.md
`vagrant-reload` plugin was not being used anymore.
> Removed vagrant-reload instructions from README.md

- container-host-files/etc/scf/config/role-manifest.yml
- tooling/lib/releases_diff.rb
- Bumped CAPI from version 1.78.0+dev.4 to 1.79.0.
- Fixed `dynamic constant assignment (SyntaxError)` on the `releases_diff.rb`.
- `cc.default_stack` changed from `cflinuxfs2` to `cflinuxfs3`.
- `cc.stacks` changed from `cflinuxfs2` to `cflinuxfs3`.
Both changes are overridden at our `opinions.yml` and `role-manifest.yml`.
All tests should pass.
> Bump CAPI to 1.79.0

- bin/common/versions.sh
This picks up fissile with a modified readiness probe to not emit as much (typically) useless and misleading output.
Just the normal CI is fine; the fissile change should just outright fail to run if it's that bad.
> bin/common/versions.sh: bump fissile

- Jenkinsfile
- bin/common/versions.sh
Contains configgin change fixing system getting stuck in HA upgrade.
Ref: https://trello.com/c/DAAtVnaR/1052-14rc2-2161-cap-ha-upgrade-doppler-1-not-coming-up
Deploy 1.3.1 Release in HA mode.
Upgrade to chart build from this PR, still HA mode.
Doppler pods should come up with no problem.
> Bump to stemcell

- container-host-files/opt/scf/bin/pod-status
If `NS` is set, we should output `--namespace ${NS}`, rather than `--namespace ${NS} ${NS}` (because the `${NS:-}` would output one copy).
Run `pod-status -n uaa` in the VM; you should only see the UAA pods (and not, for example, `kube-system`).
> pod-status: fix namespace param

- container-host-files/etc/scf/config/role-manifest.yml
The postgres release doesn't currently support HA; limit it to one replica to avoid split-brain issues when scaling up (because they function as independent databases, rather than a cluster).
Run the cluster in HA mode and run the brain tests (in particular, `018_autoscaler`).
> role-manifest: autoscaler-postgres: limit to one replica

- bin/common/versions.sh
- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
This bumps fissile to do additional checks on properties: only properties in used jobs should be allowed, etc. See cloudfoundry-incubator/fissile#496.
Also fix role manifest / opinions where they trip the new checks.
CI should be enough: the main change is in fissile (which has its own tests), this is just to make sure the configs we have still work.
Marking as draft until fissile is merged (and we don't use `checks` builds).
> fissile: bump version for additional checks

- container-host-files/etc/scf/config/role-manifest.yml
Fixed when a service account was referenced by more than one CF role, the SA definition was included in the Helm chart and not in the bosh-task Kube config file.
Build and check that `//output/kube/bosh-task/acceptance-tests-brain.yaml` and `//output/kube/bosh-task/sync-integration-tests.yaml` both include its own service account.
Check that the generated helm templates don't include test service accounts, roles, cluster roles, and bindings to these roles.
> Created and assigned separate service accounts for tests

- bin/common/versions.sh
The defered changes for https://trello.com/c/rhJZ3Rqm/1036-dont-use-deprecated-storage-class-key-in-helm-templates were merged into SCF anyway, due to us having merged them into fissile develop and later fissile changes on top then going into SCF, bringing these with them.
This PR bumps fissile to a version where the storage class work has been reverted.
This should fix https://trello.com/c/bfWaFSwT/1072-14rc3-uaa-upgrade-failed
Testing upgrades.
> Bump fissile, revert change 'storageclass annotation to key'.

- container-host-files/etc/scf/config/role-manifest.yml
Bumping the smoke-tests in order to get the following fixes:
1. [Defer cleanup so orgs do not leak](https://github.com/cloudfoundry/cf-smoke-tests/commit/f1e1d5cf45236de28c9599c3008066580acd865c)
2. [Proper setup and clean test resources](https://github.com/cloudfoundry/cf-smoke-tests/commit/e260f73b675b9225e299384ab6c9e889743de80c)
Check whether now smoke-tests are failing or not.
**Details:** https://trello.com/c/OYBbILIr/1067-cf-smoke-tests-fail-intermittently-with-no-api-endpoint-set-error
> Bumping cf-smoke-tests-release to 40.0.46

- CHANGELOG.md
- container-host-files/etc/scf/config/role-manifest.yml
There have been some commits directly on the `master` branch that do not exist on `develop` and therefore need to be merged back.
> Merge master

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Our UAA OAuth clients configuration has diverged from upstream; sync up again.
This should pass CATS.
We will need a separate PR to ensure we do not diverge more from upstream in further CF bumps.
A few of the differences are ignored:
- Upstream does not have `app_autoscaler` client (because that's not in cf-deployment)
- Upstream does not have `cf-usb` client
- Upstream does not have `scf_auto_config`
- Upstream does not have `credhub_user_cli` client
- Upstream _does_ have `credhub_admin_client` that we intentionally don't have
- We do not have `network-policy` (that's part of cf-networking)
- We do not have the `perm.admin` scope for the CF CLI (we never got that release, and it's already deprecated for being incompatible with PXC).
> Rebase UAA OAuth client configs

- container-host-files/etc/scf/config/role-manifest.yml
In a5bcada only the URL was downgraded from `36.17.0` to `36.15.0`, but the version and sha1 fields were left at the `36.17.0` settings.
> Fix version and sha1 of cf-mysql-release 36.15.0

- Vagrantfile
Use the vagrant directory to store the disk files.
Provision a Vagrant machine on a Linux host with libvirt, that doesn't have VirtualBox installed. And provision with VirtualBox as well to make sure it works as expected.
> Fixed Vagrantfile when VirtualBox is not installed

- container-host-files/etc/scf/config/role-manifest.yml
- make/run-eirini
- src/scf-release/jobs/configure-scf/spec
- src/scf-release/jobs/configure-scf/templates/run.erb
* Adds eirini-extensions and eirini-persi-broker jobs to the eirini pod
* Disables nfs-persi and enables eirini-persi-broker in postdeployment steps if eirini is enabled
```
$> make vagrant-prep
$> make run-eirini
$> git clone https://github.com/scf-samples/dizzylizard.git
$> cd dizzylizard
$> cf push --no-start
$> cf service-brokers
$> cf enable-service-access eirini-persi
$> cf marketplace -s eirini-persi 
$> cf create-service eirini-persi default eirini-persi-1
$> cf create-service eirini-persi default eirini-persi-2
$> cf bind-service dizzylizard eirini-persi-1
$> cf bind-service dizzylizard eirini-persi-2
$> cf start dizzylizard 
$> kubectl get pvc -n eirini
```
> [WIP] Add Eirini extensions and Eirini persi broker

- container-host-files/etc/scf/config/role-manifest.yml
See https://trello.com/c/Las6AWFG/1080-cf-v2-info-metadata-is-inaccurate
- Start a vagrant box.
- Build SCF
- Start cluster
- Target cluster, then `cf curl v2/info` and check that the information is correct.
> [#Las6AWFG] Bump default for cluster version returned by the v2/info endpoint

- src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
See https://trello.com/c/QeitO7T1/1086-all-minibroker-tests-will-fail-on-gke-and-possibly-other-platforms-due-to-timing-issue-in-brains-minibrokerhelperrb-library
This is a supporting change, not a fix.
It enables us to tailor the brain test timeout to the environment a cluster is running in.
- Check PR out
- Build SCF in Vagrant
- Start cluster
- Run brain tests with a command like
> make/tests acceptance-tests-brain env.**TIMEOUT=2400**
- Check the log output for the test to contain a line like
> testbrain run **--timeout 2400** /var/vcap/packages/acceptance-tests-brain/test-scripts
Important parts highlighted.
> Added ability to override the standard timeout for brain tests via environment variable `TIMEOUT`.

- tooling/bin/import-bosh-releases
Fixed a minor issue in `import-bosh-releases`
Check whether `tooling/bin/import-bosh-releases <cf-deployment-version>` is working fine.
> Fixed a minor issue in import-bosh-releases

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_garden_logdir.sh
Following modules were bumped:
```
bpm 1.0.0 -> 1.0.3
cf-cli 1.12.0 -> 1.13.0
cf-syslog-drain 8.2 -> 9.0
diego 2.25.0 -> 2.28
garden-runc 1.17.2 -> 1.18.3
loggregator 104.5 -> 105.0
log-cache 2.0.2 -> 2.1.1
statsd-injector 1.6.0 -> 1.7.0
loggregator-agent 3.3 -> 3.7
```
Updated patch `fix_garden_logdir.sh`.
Also,  `cf-acceptance-tests` bumped to match `cf v7.6`.
Make sure build is passing.
> CF bump 7.6

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_garden_logdir.sh
Following modules were bumped:
```
bpm 1.0.0 -> 1.0.2
cf-syslog-drain 8.2 -> 9.0
diego 2.25.0 -> 2.28
garden-runc 1.17.2 -> 1.18.2
log-cache 2.0.2 -> 2.1.1
statsd-injector 1.6.0 -> 1.7.0
loggregator-agent 3.3 -> 3.5
```
Updated patch `fix_garden_logdir.sh`.
Also,  `cf-acceptance-tests` bumped to match `cf v7.2`.
Make sure build is passing.
> CF bump 7.5

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
This commit also marks the 3 eirini image variables with the `imagename` attribute, but given that the current default values include the org name, it will have no effect right now.
The fissile bump also includes a bug fix for setting `FISSILE_SIZING_xxx_COUNT` correctly when `config.HA` is `true`.
> Bump fissile to include support for imagename config variables

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Includes bump to fissile version that implements the simplified model.
Jobs no longer specify a psp; there is just one psp anymore and it is bound to all service accounts.  In addition to capabilities each job now also specifies if the pod needs to be privileged.
Most of the cluster roles have been replaced by regular roles. The exceptions are the `eirini`, `node-reader`, and `test` cluster roles.
Eirini continues to run effectively as cluster-admin and will be addressed at a later time. The node-reader cluster role is required for diego-cells to be able to read the AZ label of the nodes they
are running on. The test-role is used by brain tests and not installed by the helm chart.
See also: https://github.com/cloudfoundry-incubator/fissile/wiki/ServiceAccount-and-PodSecurityPolicy-usage
> Simplify service accounts and pod security policies

- container-host-files/etc/scf/config/role-manifest.yml
There is no reason to request additional capabilities on a privileged container, or to specify an empty list of additional capabilities.
Also: I like deleting stuff! 😛
> Remove redundant capability requests from the role manifest

- bin/common/versions.sh
- make/include/defaults
- make/istio/run
- make/istio/stop
bump istio from 1.0.5 to 1.1.5 as 1.1.x have changed a lot from 1.0.x
- `make istio-run` to set up istio.
If installation complete, you'll get a deployment like below.
```
vagrant@vagrant-kube:~/scf> k get pod -n istio-system
kubectl get pod -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
grafana-77b49c55db-db62p                  1/1     Running     0          2m45s
istio-citadel-6f958bff99-lzxkz            1/1     Running     0          2m45s
istio-galley-55b7cbc6f4-mclp2             1/1     Running     0          2m45s
istio-ingressgateway-99dfd95c6-t65l5      1/1     Running     0          2m45s
istio-init-crd-10-mkkcr                   0/1     Completed   0          2m51s
istio-init-crd-11-bd2mp                   0/1     Completed   0 …
```
> bump istio from 1.0.5 to 1.1.5

- bin/common/versions.sh
- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Here are the changes in submodules:
```
cf-smoke-tests, 40.0.46 -> 40.0.50
cf-syslog-drain, 9.0 -> 9.1
credhub, 2.1.2 -> 2.1.4
diego, 2.28.0 -> 2.30.0
garden-runc, 1.18.3 -> 1.19.1
log-cache, 2.1.1 -> 2.2.0
statsd-injector, 1.7.0 -> 1.8.0
```
**Notes:**
- Added cert LOG_CACHE_CF_AUTH_PROXY_EXTERNAL_CERT.
- Limited the cf-syslog-drain health endpoint to localhost to match [upstream](https://github.com/cloudfoundry/cf-syslog-drain-release/releases/tag/v9.1).
- Updated CATs to `cf7.9`.
- Fixed issue related to TLS communication between `gorouter` and `log-cache`.
- Increased timeouts for CATs.  
Make sure the build is passing.
> CF bump 7.9

- bin/image-list.rb
- make/kube
This makes is easy to copy them to a local registry to speed up upgrades, or to move them to an air-gapped installation.
Create a new helm chart and check that the `imagelist.txt` file exists inside the chart (next to the `values.yaml` file), and that it includes the names of all "local" images. Image names that include a registry hostname, or a repository organization will not be included.
> CAP-335 Store list of all images inside the helm chart

- container-host-files/etc/scf/config/scripts/configure-az.sh
- container-host-files/etc/scf/config/scripts/configure-pz.sh
See [CAP-259](https://jira.suse.com/browse/CAP-259)
- We only have to remove the `|| true` masking the error. The script runs in a context which aborts on error.
- Rebased to head of dev. Collapsed the various back and forth in the history.
In the original submission it was `missing privileges of node-reader service account` which should have triggered the error.
Tested in local vagrant with
- Intentionally crippled `node-reader` account. (See the `verbs` of `node-reader-role` to `delete` (Cannot make it empty, that is rejected by `fissile`. Using `delete`, an irrelevant verb here, to get around that))
- Inserted `false`.
> [#UcByaqlM] [CAP-259] Force abort on errors within AZ and PZ handling.

- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/acceptance-tests/spec
- src/scf-release/jobs/acceptance-tests/templates/run.erb
- src/scf-release/jobs/sync-integration-tests/spec
- src/scf-release/jobs/sync-integration-tests/templates/run.erb
CATS often has random failures on Jenkins that are due to resource pressure and not reproducible. -flakeAttempts tells Gingko to retry failed tests multiple times before treating them as failures. Each
individual failed test will still be reported, just not reflected in the exit code.
[CAP-99]
> CAP-99 Provide a mechanism to set -flakeAttempts when running CATS

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/acceptance-tests-brain/spec
- src/scf-release/jobs/acceptance-tests-brain/templates/environment.sh.erb
- src/scf-release/src/acceptance-tests-brain/test-resources/policy.json
- src/scf-release/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb
Ref: https://github.com/SUSE/scf/pull/2364
**JIRA:** https://jira.suse.com/browse/CAP-251
1. Make sure the build is passing
2. Test upgrades from CAP 1.4
3. Must be tested on CaaSP as per IBM
> Bump autoscaler to 1.2.1

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Submodule changes:
```
bpm, 1.0.3 -> 1.04
cf-smoke-tests, 40.0.50 -> 40.0.51
cf-syslog-drain, 9.1 -> 10.0
credhub, 2.1.4 -> 2.2.0
loggregator, 105.0 -> 105.2
routing, 0.184.0 -> 0.187.0
statsd-injector, 1.8.0 -> 1.9.0
loggregator-agent, 3.7 -> 3.9
```
**Notes:**
- Made changes for enabling TLS between trafficcontroller and gorouter. Refer [this](https://github.com/cloudfoundry/loggregator-release/releases/tag/v105.1).
- Switched to using `log-cache` instead of `traffic_controller` for retrieving container metrics. Refer [this](https://github.com/cloudfoundry/loggregator-release/releases/tag/v105.0).
Make sure the build is passing.
> CF Bump 7.11

- deploy/helm/scf/assets/operations/instance_groups/database.yaml
It starts the database and tails the combined logs, waiting for the pid to exit.
- When using `kubectl log ...` with the database, it should tail the combined logs.
- When killing the database with `kill -SIGTERM $(cat /var/vcap/sys/run/mysql/mysql.pid)` inside the database container, it should restart the container.
> Add proper database command

- deploy/helm/scf/assets/operations/instance_groups/nats.yaml
Added the ports, and readiness and liveness probes.
Nats should become ready and live only after it's appropriately listening on ports 4222 and 4223.
> Add nats bosh_containerization properties

- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
Adding `diego-cell` instance group with `garden` only.
With Minikube, it will require the use of the openSUSE Minikube image that currently only works with Virtualbox vm-driver.
1. Start Minikube with `--iso-url=https://github.com/f0rmiga/opensuse-minikube-image/releases/download/v0.1.0/minikube-openSUSE.x86_64-1.0.0.iso`.
2. Deploy the lastest master of `cf-operator`.
3. Deploy SCF.
> Add garden job to diego-cell instance group

- src/scf-release/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb
This will provide more info whenever the autoscaler test is failing.
Original ref: https://github.com/SUSE/scf/pull/2364/commits/0986ccf71d5dadd547aaec4f49845178698ba2c4
Make sure the build is passing.
> Adding a check for retrieving cf stats in the autoscaler test

- bin/common/versions.sh
Bumped version number for next CAP release associated with this scf build
n/a. need to find the appVersion entry too since that ties into the helm chart
> prep for next CAP release v1.4.1

- README.md
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/cc_migration_squash.sh
- tooling/helpers/0001-db-migration-add-script-to-squash-DB-migrations.patch
As MySQL / MariaDB does *not* support transactions around schema modifications, we still need to do something about the high frequency of database migration failures (migrating from an empty database) because something hiccuped in the middle.  So this patch squashes all the existing schema migrations (up to SCF 2.16.4 / capi-release 1.79.0) into one giant migration.  The initial migrations will also drop any existing tables (so if we _do_ get interrupted we still have a good chance of recovery).  This is of course not done if the last table to be created already exists (so we don't lose data).
Start a cluster, and break the MySQL connection to the database halfway through migration (possibly by terminating the switchboard process, or editing the service to have no endpoints).  When the …
> instance_groups/api_group: patch to use squash migrations

- README.md
- make/run
- make/upgrade
Updates to the README and `make/run`, `make/upgrade` scripts. The scripts print the `helm` command they invoke to make inspection during debugging easier.
__Note__, the subordinate PR for UAA = https://github.com/SUSE/uaa-fissile-release/pull/161
implements the feature to override the chart, existing in SCF for some time, in UAA as well.
Build and deploy on vagrant, check that `make/run` prints a `helm install ...` line, and that a simple `make/upgrade` prints a `helm upgrade ...` line. This also happen for the subordinate UAA deployment.
> Vagrant utility work

- bin/common/versions.sh
> Bump fissile to generate serviceAccountName even for default sa

- container-host-files/opt/scf/bin/pod-status
On a multi-node cluster with ingress, minibroker, scf, stratos, and uaa deployed the list of pods already fills the screen. Including kube-system pods pushes some entries below the bottom, making them invisible to `pod-status -w`.
> Exclude kube-system namespace from pod-status output

- container-host-files/etc/scf/config/scripts/configure-az.sh
E.g. `-o 'jsonpath={.metadata.labels.foo\.bar}}'`
or `-o "jsonpath={.metadata.labels['foo\.bar']}"`
Even the [bracket] version requires the dot to be backslash-escaped.
> Fix NODE_AZ query in case the label contains dots

- Jenkinsfile
Because this is a relatively new variable, the pipelines may not define the variable for new PRs yet, throwing errors like:
```
.../script.sh: line 21: EMBEDDED_UAA: unbound variable
```
> Include default EMBEDDED_UAA value in all Jenkinsfile bash scripts

- container-host-files/etc/scf/config/role-manifest.yml
This is the predefined (well-known) label reserved for this purpose:
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
Test show that kube installations provided by public cloud providers already set this label on their nodes.
> Set AZ_LABEL_NAME to failure-domain.beta.kubernetes.io/zone

- container-host-files/etc/scf/config/role-manifest.yml
This reverts commit 75ade779a8bdd4b8ba1264e6a579601e2436c223.
The bump is making the  build unstable by introducing failures in brains(possibly CATs) while staging Dora app.
Make sure brains and CATs are passing.
> Reverting ruby-buildpack bump

- container-host-files/etc/scf/config/scripts/patches/cc_migration_squash.sh
- tooling/helpers/0001-db-migration-add-script-to-squash-DB-migrations.patch
Ruby doesn't like `break` there (we get an error saying "LocalJumpError: break from proc-closure"); try using `next` instead.
- Deploy SCF as normal
- Kill the `api-group` pod halfway through the migration (after the `users` table is created, but before Sequel records that fact).
> ccdb migration squasher: fix ruby syntax error

- deploy/helm/scf/assets/operations/instance_groups/database.yaml
Since the BPM persistent disk is mounted on /var/vcap/store/mysql, the
original script that runs the database setup stopped running, as the
creation of this directory itself was done as part of the pre-start
setup. The patch introduced in this commit fixes that by switching the
logic to a file inside that folder.
The database should work again, and UAA should connect to it successfully.
> Fixed database with BPM persistent disk

- container-host-files/etc/scf/config/role-manifest.yml
Ref: https://jira.suse.com/browse/CAP-385
Subordinate UAA PR: https://github.com/SUSE/uaa-fissile-release/pull/164
- Build a cluster in vagrant as usual.
- After and/or during startup inspect the kube logs of the secret generation pods.
The output from the cert generations should be interleaved instead of serial.
Note: As UAA has not as many certs to generate than SCF the amount of interleaving is limited, pure randomness can make it look mostly serial.
> Bump scf helper to version including the SSG modified for parallel cert generation.

- .gitignore
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
Bumped the default stemcell version and added the api instance group with the cloud_controller_ng job and the binary buildpack.
Deploy the cf-operator and on SCF:
```
bazel build //deploy/helm/scf:chart && helm template --name scf bazel-bin/deploy/helm/scf/scf-3.0.0.tgz --namespace scf --set "system_domain=$(minikube ip).xip.io" | kubectl apply -f - --namespace scf
```
> Add api instance group with cloud_controller_ng

- rules/helm/BUILD.bazel
- rules/helm/def.bzl
- rules/helm/package.sh
Moved packaging logic to a standalone script to make it "lintable" and easier to maintain.
`bazel build //deploy/helm/scf:chart` should produce the chart package under `bazel-bin/deploy/helm/scf/scf-3.0.0.tgz`.
> Moved packaging logic to a standalone script

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
The linking bug was solved, therefore, no need for this anymore.
Blobstore should not fail when resolving these link properties from the CC provider.
> Removed default properties being overritten due to bug

- bosh/releases/pre_render_scripts/log-api/loggregator_trafficcontroller/patch_bpm.sh
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
See https://jira.suse.com/browse/CAP-515
Note: Only the `trafficcontroller` job is activated here.
The other jobs
- reverse-log-proxy
- reverse-log-proxy-gateway
- route-registrar
are still disabled, and will be activated in future PRs, as needed.
- Start a local kube cluster (minikube, or kind).
- Start modified scf, see log-api role being green.
> SCF v2 - Enable log-api instance group and jobs

- make/kube
This ensures that the /v2/info endpoint will have the correct values automatically.  Should help us avoid shipping with the wrong version in the future.
Run `make helm` (or do it via Jenkins), and check that `CLUSTER_BUILD` is 2.17.1 (from the git tag); alternatively, check that the `/v2/info` endpoint responds with a build of 2.17.1.
> make/kube: update CLUSTER_BUILD from git tag

- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/assets/operations/temporary/remove_addons.yaml
The current state of cf-operator doesn't allow addons to work as it is currently setup on v2-develop. This PR removed them so we can add them accordingly on a separate branch.
SCF should come up with the latest cf-operator.
> Remove addons

- dev/kind/BUILD.bazel
- dev/kind/def.bzl
- dev/minikube/BUILD.bazel
- dev/minikube/def.bzl
- dev/scf/BUILD.bazel
The bash completion included in bazel seems to want the convention where
things we `bazel run` are written with rules ending in `_binary`; also,
`bazel test` targets should be written with rules ending in `_test` or
be named `test_suite`.
This fixes auto-completion for me.
Make sure `bazel run //dev/kind:start`, etc. still work.
If you have bash completion, check that `bazel run //dev/kind:` completes `start`, `delete`.
> Make `bazel run` targets use rules ending in `_binary`

- Jenkinsfile
- make/include/versioning
This branch modifies the Jenkins build process such that when it is built from the `release-candidate` branch, it does some extra things:
- Drops the `-rc?` suffix on the artifacts (so it looks like a release build).
- Tags the repo with the RC release number (so we can go back and look at it).
- Jenkins will only build this on a manual trigger, or updating the [change log](https://github.com/SUSE/scf/blob/develop/CHANGELOG.md).
Please check the new `scf-release-candidate` Jenkins pipeline (not linking because this is a public PR). It's currently set up to build from the PR branch instead of the final RC branch, but otherwise it should be the same.  I manually deleted the extra `0.0.0-rc1` tag it created (I modified the changelog so the top entry was version `0.0.0`).
> Release candidate support

- deploy/helm/scf/assets/operations/set_release_urls.yaml
- deploy/helm/scf/templates/_helpers.tpl
- deploy/helm/scf/templates/implicit_vars.yaml
- deploy/helm/scf/values.yaml
This lets us change the release URLs (actually the docker org for the images to use); also, refactor how we do implicit variables a bit to reduce duplication.
No change to default behaviour.
Closes jsc#CAP-553.  Supercedes #2601 (due to the change in the base branch).
A normal `bazel run //dev/scf:apply` should have no changes. However, we should now be able to override the prefix to something different (which will not work because we don't have those images)
> Make the release URLs customizable

- bosh/releases/pre_render_scripts/api/cloud_controller_ng/patch_bpm.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/remove_tee_output_to_sys_log.sh
- bosh/releases/pre_render_scripts/api/routing-api/patch_bpm.sh
- bosh/releases/pre_render_scripts/database/mysql/patch_pre-start-setup.sh
- bosh/releases/pre_render_scripts/log-api/loggregator_trafficcontroller/patch_bpm.sh
- bosh/releases/pre_render_scripts/shared/route_registrar/patch_bpm.sh
- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/patch_blobstore_conf.sh
- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/patch_blobstore_pre-start.sh
- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/patch_job_mf.sh
- bosh/releases/pre_render_scripts/uaa/uaa/patch_pre-start.sh
- bosh/releases/pre_render_scripts/uaa/uaa/patch_uaa.sh
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
After doing a `grep -r -B 10 "service.cf.internal" /var/vcap/jobs/` on each statefulset, it revealed that many `*.service.cf.internal` addresses were still there.
```
for pod in $(kgpon scf -o name); do
kexn scf "${pod#"pod/"}" -- bash -c 'grep -r -B 10 "service.cf.internal" /var/vcap/jobs/'
done
```
should return no `service.cf.internal` addresses.
> v3 - Fixed remaining *.service.cf.internal addresses

- dev/minikube/start.sh
This makes it easier to test VBox images on a machine using kvm2 as default, or vice versa.
Check that `VM_DRIVER=kvm2 bazel run //dev/minikube:start` and `VM_DRIVER=virtualbox bazel run //dev/minikube:start` use different VM drivers.
Use `minikube config set vm-driver kvm2` (or `… virtualbox`) to change the default VM driver.
> //dev/minikube:start: Allow overriding VM driver

- rules/helm/package.sh
Running on mac, where the `cp -L --recursive` in rules/helm/package.sh fails. This PR worked on replacing `cp` command with `rsync`. Most machines will have rsync available.
Run `bazel run //dev/scf:apply --verbose_failures --sandbox_debug` on different OS.
> Copy folder on darwin OS

- bosh/releases/generators/pre_render_scripts/generator.sh
- bosh/releases/pre_render_scripts/README.md
- deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/nats.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/scf/templates/bosh_deployment.yaml
- dev/scf/.gitignore
- dev/scf/BUILD.bazel
- dev/scf/values.yaml
`cf-operator` has 2 breaking changes on the current master that we should update here:
1. `bosh_containerization` was renamed to `quarks`.
2. `spec.ops.ref` was renamed to `spec.ops.name`, and `spec.manifest.ref` was renamed to `spec.manifest.name`.
This branch should work with `cf-operator` master.
> v3 - Fix breaking changes related to cf-operator

- chart-parts/eirini-namespace.yaml
- container-host-files/etc/scf/config/role-manifest.yml
Instead we create an eirini role with full access inside the eirini namespace and bind it to the eirini service account in the release namespace.
Replaces #2520.
[jsc#CAP-485]
Deploy SCF with `--set enable.eirini=true` and verify that you can push an app.
> Get rid of cluster-admin binding for the eirini service account

- bin/dev/kube-ready-state-check.sh
Adds a minimal kernel check version to bin/dev/kube-ready-state-check.sh.
Run `bin/dev/kube-ready-state-check.sh`, see that it shows:
```
Verified: nodes should have kernel version 3.19 or higher
```
or
```
Configuration problem detected: nodes should have kernel version 3.19 or higher
```
Already tested and working on all cases:
```
bash ~/code/cap/scf/bin/dev/kube-ready-state-check.sh
Testing all
...
Verified: nodes should have kernel version 3.19 or higher
...
```
Changed min_ver to `4.19`, where the installed kernels are `4.12`, to make it fail:
```
$ bash ~/code/cap/scf/bin/dev/kube-ready-state-check.sh
Testing all
...
Configuration problem detected: nodes should have kernel version 4.19 or higher
...
```
Changed the min_ver to `4.12.14-197.15-default`, same as installed, to make it …
> Add min kernel check version to bin/dev/kube-ready-state-check.sh

- dev/minikube/def.bzl
Bumping the openSUSE Minikube image that fixes the DNS issues we were seeing.
DNS queries should resolve external names.
> v3 - Bumped openSUSE Minikube image to 0.1.3

- dev/minikube/def.bzl
This fixes the Docker daemon not being reachable from the host on Virtualbox.
Should work on both KVM and Virtualbox.
> Bumped openSUSE Minikube image to 0.1.4

- Jenkinsfile
It's kind of annoying to have klogs for SCF, but not UAA, when a lot of the time we're failing tests because (we suspect) UAA fell over.  So this pulls the UAA logs first, so they'll show up when we bundle the SCF logs.
1. Get a Jenkins build that fails
2. Check that the uploaded logs contains UAA bits.
> Jenkinsfile: add logs of UAA on failure

- deploy/helm/scf/templates/single_availability.yaml
derived from https://www.pivotaltracker.com/story/show/167851849, this PR will fix this one. And I opened a story to track Bosh AZs support if anything lost.
cf-operator will define required node affinities when setting `ExtendedStatefulSetSpec.Zones` which come from `instance_groups.azs`. After cf-operator applies node affinities, scf will be blocked if kube nodes have not required labels such as (`failure-domain.beta.kubernetes.io/zone: z1`).
For single availability, it **should not** set any AZs for ExtendedStatefulSets. Because it doesn't need any node affinity and we don't need more node labeling operations.
For high availability, the statefulsets count of instance group = AZs * instances. That's what we designed: https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/ …
> v3 - Remove `azs` for single zone

- Jenkinsfile
- bin/common/versions.sh
This pulls in the new configgin 0.18.8, which has a fix for restarting pods when the BOSH links they import changes.
See also: https://github.com/cloudfoundry-incubator/configgin/pull/104
- Run SCF
- Check that the diego-ssh StatefulSet has the annotation on importing properties from cloud_controller_ng
> Jenkinsfile, version.sh: Bump fissile stemcell version

- container-host-files/opt/scf/bin/recovery-autoscaler-metrics-liquidbase-stale-lock
This adds a script that attempts to recover a stale lock for the `autoscaler-metrics` database.  This can occur if the `autoscaler-metrics` pod was terminated while it's holding the lock, as for some unfathomable reason the library implements locking by inserting data into a table, instead of just using actual (possibly row-level) locking.
1. Deploy SCF, and wait for everything to be ready.
2. Delete the `autoscaler-metrics` pod.
3. Watch the logs of the `autoscaler-metrics` container as the pod restarts.
4. Delete the pod again once you see the `Starting Liquibase at`… message.
5. Wait for the respawned pod until you see error traces about `liquibase.exception.LockException: Could not acquire change log lock.`
6. Run the script and see that it fixes things.
> New script to attempt to recover stuck lock

- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
This fixes the error on `cloud_controller_ng`:
```
E0822 21:19:47.976388536     662 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```
> v3 - Fixed cloud_controller_ng -> log-cache mTLS

- bin/common/versions.sh
[jsc#CAP-628]
When deploying SCF with Diego, neither the `configure-eirini` job nor the `eirini-copy-certs` pod should be created.
> Bump fissile to add support for feature flags to jobs

- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/templates/implicit_vars.yaml
- deploy/helm/scf/values.yaml
This allows us to configure the default stemcell.  Note, however, the image name is still constructed via joining various parts; it's
`((releases-defaults-url))/((release-name)):((stemcell-os))-((stemcell-version))-((release-version))`.
- Run a normal build, everything stays working
- Edit `dev/scf/values.yaml` to add `stemcell: { os: foo, version: bar }` and see the different docker image used when you apply (check the `bpm` pod).
I'm happy to modify the helm chart `values.yaml` layout &c. if there are better names / placements for things.  I tried to put it under `releases/defaults` but it didn't seem to make any sense.
> jsc#CAP-554: Allow default stemcell to be configured

- deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
- deploy/helm/scf/templates/implicit_vars.yaml
- deploy/helm/scf/values.yaml
It breaks addons. This needs to take into account inclusive placement rules.
Reverts SUSE/scf#2705
> Revert "jsc#CAP-554: Allow default stemcell to be configured"

- chart-parts/ingress.yaml
- container-host-files/etc/scf/config/role-manifest.yml
I couldn't find any documentation about how ingress handles overlapping rules; I hope they will be processed in order, so have sorted the more specific host names first:
```
- host: "*.uaa.{{ .Values.env.DOMAIN }}"
- host: "uaa.{{ .Values.env.DOMAIN }}"
- host: "*.{{ .Values.env.DOMAIN }}"
```
I found some references to "longest prefix first", but it is not clear how this interacts with wildcard notation.
jsc#CAP-675
> Provide ingress controller for embedded UAA feature

- dev/cf_cli/README.md
- dev/cf_cli/cf_cli.sh
This temporary script helps with accessing the CF cluster from within the k8s cluster.
1. Deploy SCF v3.
2. Execute the `cf_cli.sh` script.
3. Check that the `cf-terminal` pod was created and configured the cf-cli.
4. Get a shell session to the `cf-terminal` pod and perform cf-cli operations.
> v3 - Added temporary cf_cli.sh for creating cf-cli pod

- def.bzl
`kubectl` should report version 1.14.6.
```
bazel run @kubectl//:kubectl -- version
```
> v3 - Bumped Kubernetes version to 1.14.6

- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/override-default-stack.sh
because Eirini currently doesn't work with any of the other bundled stacks, so better make the one that works the default
[jsc#CAP-721]
Deploy with Diego and check that `cf push` uses the `sle15` stack.
Deploy with Eirini and check that `cf push` uses the `cflinuxfs3` stack.
> Change DEFAULT_STACK to cflinuxfs3 when Eirini is enabled

- WORKSPACE
- def.bzl
- dev/linters/shellcheck.sh
- rules/external_binary/BUILD.bazel
- rules/external_binary/def.bzl
Now that shellcheck publishes OS X binaries (not just Linux and Windows ones), it's easy to manage all the shellcheck binaries using Bazel.
Run `//dev/linters/shellcheck.sh` from a Linux, a Mac and a Windows machines.
> v3 - Shellcheck managed by Bazel

- deploy/helm/scf/assets/operations/buildpacks/set_suse_buildpacks.yaml
- deploy/helm/scf/templates/bosh_deployment.yaml
- deploy/helm/scf/templates/ops.yaml
- deploy/helm/scf/values.yaml
The `set_suse_buildpacks.yaml` ops-file is applied before any other ops-files and it will replace the cf-deployment buildpacks with the SUSE buildpacks that contain the SLE stack.
The CI should pick the ops-file and build the SUSE buildpacks.
> v3 - Added set_suse_buildpacks ops-file

- chart-parts/_helpers.tpl
- chart-parts/cluster-roles.yaml
- chart-parts/eirini-namespace.yaml
- chart-parts/ingress.yaml
- chart-parts/opi-registry-service.yaml
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/set-opi-registry-port.sh
The old mechanism of using a docker cert copying daemon set does not work with non-docker based container runtimes. It also has problems when the host filesystem is not writable by the daemon set.
The new mechanism uses the kube certificate service to sign a cert for the registry. This still requires the kube CA to be installed such that the container runtimes on each worker node will trust it.
This commit uses a nodePort service on `127.0.0.1` for the registry:
* Can't use `registry.$DOMAIN` because it uses the wildcard cert from the gorouter. Also we don't want to expose the registry publicly.
* Can't use `bits-bits-service.$NS.svc.cluster.local` because the name doesn't resolve outside the cluster (container runtime cannot pull from there).
* Can't use `localhost` because it doesn't …
> Use kube csr feature for opi-registry in eirini

- deploy/helm/scf/templates/bosh_deployment.yaml
- deploy/helm/scf/values.yaml
Given an existing ops-file as configmap in the namespace, this allows it
to be referenced in the BOSH deployment custom resource through the
operations.custom Helm value.
Resolves #2815.
Create a random ops-file as a configmap in the SCF namespace:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: <configmap_name>
data:
ops: |-
<some_random_ops>
```
When deploying SCF, add to the values:
```yaml
operations:
custom:
- <configmap_name>
```
Then assert that the ops-file was applied.
> v3 - Allowed custom ops-files to be referenced as configmaps

- bin/common/versions.sh
This picks up cloudfoundry-incubator/fissile#515 to add support for Kubernetes 1.16
> bin/common: bump fissile version

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
We don't need it; we can just talk directly to the blobstore.
For Eirini we need the bits registry, but even Eirini's recipe up- and downloaders will talk to blobstore if bit-service is not enabled.
All this allows us to use just `127.0.0.1` as the common name for the bits ssl cert. This is important on EKS because the kube cert signer does not support subject alternate names, so the cert can
only have a single name, and it MUST be the registry address for it to be trusted by the container runtime.
[jsc#CAP-587]
> Get rid of bits-service

- container-host-files/etc/scf/config/role-manifest.yml
Controlling ticket is https://jira.suse.com/browse/CAP-168
Role manifest update for testing a new scf-helper release.
Subordinate UAA PR = https://github.com/SUSE/uaa-fissile-release/pull/168
Subordinate scf-helper PR = https://github.com/SUSE/scf-helper-release/pull/24
- Check this branch out somewhere (`/path/to/scf-checkout`).
Update the submodules to get the associated UAA PR.
- Get a checkout of https://github.com/SUSE/scf-helper-release/pull/24
- In the check out run
```
bosh reset-release
bosh create-release --force --tarball /path/to/scf-checkout/output/scf-helper-release.tgz
```
- In the SCF checkout start a vagrant box as usual
- Build as usual.
- Start as usual.
- Place
```
#!/bin/bash
N="${1:-cf}"
kubectl describe svc -n "${N}" mysql-proxy-proxy | grep -v ^Target | grep -v …
```
> Added leader election for mysql-proxy switchboard.

- container-host-files/etc/scf/config/role-manifest.yml
On CaaSP4 we often see the `bits-0` pod hanging because `monit` does not properly detect the running `bitsgo` process. Hopefully changing to `bpm` will avoid this issue. Even if it doesn't, it is still a useful change because now the bits-service will run under the `vcap` user and not as `root`.
[jsc#CAP-748]
> Enable BPM for bits-service

- Jenkinsfile
- make/include/versioning
This makes a couple separate changes to RC releases:
- Always build RC builds, don't filter based on changes.  This needs to be coupled with disabling polling in Jenkins, so that we must manually trigger all builds.
- Upload bundles on RC & nightly after testing, for jsc#CAP-631
- Keep the `-rc1` suffix in the release artifacts, so that we can push them directly to the helm repo.  Unfortunately this means the output will _not_ match the final bits. :warning: please review this more and make sure this is what we want.
- Set `GIT_TAG` to an RC release manually
- `make bundle-dist`
> Changes to RC pipeline

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/packages/sql-readiness/packaging
Ticket: https://jira.suse.com/browse/CAP-711
Subordinate pull requests:
- https://github.com/SUSE/uaa-fissile-release/pull/171 (included here as submodule)
- https://github.com/SUSE/scf-helper-release/pull/26 (See test description for integration for testing. After testing, __before merge__ :warning:, an update to the role manifests of UAA and SCF is required.)
:warning: This PR moots https://github.com/SUSE/scf/pull/2741 :warning:
This adds the option to use an external database server for the
CF-internal databases (CCDB, CF-USB, etc.), and UAA. This lets
administrators handle their own database backups if necessary.
A new job (found in the scf-helper-release) is used to initialize the
databases, using the same configuration that the mysql-release uses in
mariadb_ctrl.  The user must …
> Added support for external database server for CCDB &c.

- container-host-files/etc/scf/config/scripts/check_swapaccounting.sh
Ref: https://jira.suse.com/browse/CAP-787
Change causes generation of more tracing logs in the script checking for swap accounting vs swap. More insight into the conditions tested, and results gotten, for debugging.
Built in a vagrant box, started the cluster, and checked the kube logs of diego-cell to contain the commands from this script, plus results, etc.
> More tracing in the swap account checks.

- deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
- deploy/helm/scf/assets/operations/instance_groups/api.yaml
- deploy/helm/scf/assets/operations/instance_groups/cc-worker.yaml
- deploy/helm/scf/assets/operations/instance_groups/database.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/scf/assets/operations/instance_groups/nats.yaml
- deploy/helm/scf/assets/operations/instance_groups/router.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
This series of commits adds liveness and readiness probes for most jobs (I didn't touch the addons yet).
In general, the liveness probes are mostly checking that the correct process is running.  The readiness probes check for a health endpoint where available; some of them check `ppro` or `expvar` output, which isn't exactly correct but at least checks that something responds.  Unfortunately most processes do not have truly useful health check endpoints.
Notably, UAA & CCNG do not have liveness probes set, as they both have a long bootstrap step (cert import and db migration / seeding, respectively) that is run under a different executable.  We may be able to get away with moving those into pre-start steps, but that would have to be separate PRs. (And IIRC, we did do so for CCNG, but it …
> Add liveness & readiness probes

- Jenkinsfile
Added `Nightly` to the list of buildtypes for which to send mail on failure.
See https://jira.suse.com/browse/CAP-659
This will be tested by manually triggering a nightly scf-develop build.
> Send mail for `Nightly` builds too. They are a variant of `Develop`.

- deploy/helm/scf/templates/_helpers.tpl
- deploy/helm/scf/templates/bosh_deployment.yaml
- deploy/helm/scf/templates/properties.yaml
- deploy/helm/scf/values.yaml
Adding a mechanism that allows a user to provide job properties via Helm values.
Resolves #2766 
Set some properties and assert they took effect. E.g. add the following to `values.yaml`:
```yaml
properties:
adapter:
adapter:
quarks:
ports:
- name: adapter
protocol: TCP
internal: 4443
- name: another
protocol: TCP
internal: 7171
scalablesyslog:
adapter:
logs:
addr: scf-log-api:8082
```
> v3 - Added mechanism for allowing user provided job properties

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Switch from multi-stack buildpacks to stack associated ones.
cflinuxfs3 buildpacks are now directly taken from the upstream (bosh.io).
Only the java buildpack is not stack associated, as it is the case for upstream.
> Add stack associated buildpacks

- Vagrantfile
- vagrant/create_kubeconfig.sh
The default http endpoint bypasses RBAC validation, so all requests are accepted. Which also means that `kubectl --as` doesn't work.
Verify that you can run commands as a restricted service account, and make sure commands that are not supposed to be allowed actually fail, e.g.
```
vagrant@vagrant-kube:~> kubectl --as system:serviceaccount:default:default cluster-info
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server (Forbidden): services is forbidden: User "system:serviceaccount:default:default" cannot list resource "services" in API group "" in the namespace "kube-system"
```
> Create ~/.kube/config with https endpoint to use RBAC

- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Fixes a typo from #2860.
`kubectl --output` takes an argument; `--output-wide` is not a flag.
> acceptance-tests-brain: testutils: fix typo

- deploy/helm/scf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/scf/assets/operations/temporary/cf-acceptance-tests-stemcell.yaml
- deploy/helm/scf/templates/bosh_deployment.yaml
- deploy/helm/scf/templates/ops.yaml
- deploy/helm/scf/values.yaml
- testing/README.md
- testing/acceptance_tests/BUILD.bazel
- testing/acceptance_tests/README.md
- testing/acceptance_tests/trigger.yaml
Add initial support for CATS; it runs as an ejob, same as smoke tests.
Requires BOSH release [mook-as/cf-acceptance-tests-release].
[mook-as/cf-acceptance-tests-release]: https://github.com/mook-as/cf-acceptance-tests-release/
Does not pass yet; this is just for the initial support so we can start looking at the failures.
- Deploy SCF
- Wait for everything to go green
- Edit the `acceptance-tests` ejob to have a `strategy` of `now` to trigger the job
- We need a pipeline for building the BOSH release later (and a better home for the release)
- See also mook-as/cf-acceptance-tests-release#1
> Initial commit of acceptance tests

- bin/dev/kube-ready-state-check.sh
- Detect cri-o, disable docker check.
- Extend apiserver check to find the process in CaaSP4
- Make missing `containerd` service/process a note, not an error.
See https://jira.suse.com/browse/CAP-749
Currently only manual. Uploaded to a CaSSP4 host, executed with category `all`.
> Modify kube checker script for CaaSP4 environment.

- container-host-files/etc/scf/config/opinions.yml
- container-host-files/etc/scf/config/role-manifest.yml
Move the persi extension in a separate instance group and bind to a service listening on 443. This should allow deployments on GKE and on EKS.
Needs: ~https://github.com/cloudfoundry-community/eirini-bosh-release/pull/57~ ~https://github.com/SUSE/eirini-persi/pull/10~ ~https://github.com/SUSE/eirinix/pull/9~
Supersedes: https://github.com/SUSE/scf/pull/2738 https://github.com/SUSE/scf/pull/2846
CAP-720
> Use persi as a service

- deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
Instead of hardcoding the pod ordinal, we should rely on the label that the cf-operator sets for us. This will allow HA setups.
> Set INSTANCE_ID to reference pod-ordinal label

- Jenkinsfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
* Bump to stemcell to include new configgin version.
* Bump to fissile to set `KUBERNETES_CONTAINER_NAME`.
* Provide access to secrets from configgin role.
* Bump to uaa for secrets access from configgin role.
This can be tested locally with the `./update-stemcell.sh` script from the configgin repo while the new stemcell is not yet available.
> Bump configgin to store exported properties in secrets

- Jenkinsfile
We changed configgin to put exported BOSH properties in secrets; the Jenkins test for rotated secrets is now failing to find the correct secret.  We need to update it to locate the correct secret.
Jenkins builds are failing with:
`Secret \${secret_name} not correctly rotated`
This will trigger CI
> Jenkinsfile: Get the correct secret when testing rotation

- Jenkinsfile
This is the `rc` version of #2998.
`git config --unset-all` will return an error value if the thing to unset wasn't set to start with. Work around this by checking if it exists first.
We are getting failures trying to build the RC because things are bailing halfway through.
Jenkins will deal with it.
```
12:30:05 + set -o errexit -o nounset
12:30:05 + git config --local --replace-all credential.helper '/bin/bash -c "echo "username=${GIT_USERNAME}"; echo "password=${GIT_PASSWORD}""'
12:30:05 + git config --unset-all versionsort.suffix
…
ERROR: script returned exit code 5
```
> Jenkins: git: don't fail when unsetting versionsort

- make/kube
The apiVersion field in helm's Chart.yaml is for the Helm API version, and not for the app version.  We still have appVersion and version tags.
jsc#CAP-817
This is breaking the Eirini pipeline.
> make/kube: use correct helm apiVersion

- make/kube
Helm ignores additional fields, and we need to carry on metadata to
identify the chart versioning (cf version, commit hash).
The commit is not only useful to identify the chart, but it is actually
used by pipelines to match SCF tags against the released charts.
CAP-877
> Annotate APP_VERSION to a custom Chart field

- container-host-files/etc/scf/config/role-manifest.yml
Reactivated the default state for pxc binlog: enabled=true.
Subordinate UAA PR = https://github.com/SUSE/uaa-fissile-release/pull/176
Ticket: https://jira.suse.com/browse/CAP-990
PXC falls over after a restart with the following errors seen in the pxc-mysql log:
```
2019-09-10T20:02:57.636429Z 0 [ERROR] Found 1 prepared transactions! It means that mysqld was not shut down properly last time and critical recovery information (last binlog or tc.log file) was manually deleted after a crash. You have to start mysqld with --tc-heuristic-
recover switch to commit or rollback pending transactions.
2019-09-10T20:02:57.636437Z 0 [ERROR] Aborting
```
This appears to be happening due to the fact that binlogs are not turned on when galera is turned off which is the default setup: …
> Go to the default of an active binlog for our pxc config.

- container-host-files/etc/scf/config/role-manifest.yml
Added `suse-` prefix on the job names in the buildpack bosh releases to make it easier for kubecf code to distinguish between upstream jobs and our jobs. cc @f0rmiga
> Bump buildpacks to use the renamed jobs

- CHANGELOG.md
Eirini uses sle15 as its default stack, not cflinuxfs3.
> CHANGELOG Fixes

- src/scf-release/src/acceptance-tests-brain/test-scripts/minibroker_helper.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/testutils.rb
Plus additional output to better demarcate code locations and sections.
Additional output statements to mark code sections in verbose log output.
Change `wait_for_namespace` to get status of kubectl command instead of aborting in the low level. Failure may be a glitch in the kube foundation. Treat it as __namespace not ready__ and continue retrying to overcome.
References:
- https://jira.suse.com/browse/CAP-1043
- https://jira.suse.com/browse/CAP-1042
In the vagrant box, started a cluster, and ran brain tests `01[24]_*` to see modified output and that the change is not breaking successful runs.
> Retry various helm/kubectl failures to overcome low-level glitches

- Jenkinsfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- container-host-files/etc/scf/config/scripts/patches/fix_logcache_ca_cert.sh
- container-host-files/etc/scf/config/scripts/patches/set_logs_provider_addr.sh
- src/scf-release/jobs/configure-scf/templates/run.erb
- src/scf-release/jobs/uaa-create-user/templates/run.erb
- src/scf-release/jobs/wait-for-uaa/templates/pre-start.erb
Break all cyclic dependencies on bosh links because they are incompatible with the new configgin version that sequences pod startup so that all imported properties (via bosh links) are generated before the pod starts.
Also includes various changes to speed up deployment in general.
Initial testing involves just watching the deployment and verifying that pods don't restart after entering `Running` state. The whole cluster should become ready much faster than before this PR, but otherwise operate unchanged.
Extended testing should include HA deployments, scaling up instance counts, secrets rotation, and updates, both from the previous release, as well as to a hypothetical next release, that also uses the new configgin mechanism.
> Avoid pod restarts

- chart-parts/NOTES.txt
When Eirini is deployed without `--set env.KUBE_CSR_AUTO_APPROVAL=true` then the secret generator will wait until an admin approves the request before deployment continues, and this can be non-obvious to the user.
> Ask for CSR approval at the end of NOTES.txt

- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
- src/scf-release/jobs/acceptance-tests-brain/spec
- src/scf-release/jobs/acceptance-tests-brain/templates/environment.sh.erb
- src/scf-release/jobs/acceptance-tests-brain/templates/pre-start.erb
- src/scf-release/jobs/acceptance-tests/templates/pre-start.erb
- src/scf-release/jobs/authorize-internal-ca/spec
- src/scf-release/jobs/authorize-internal-ca/templates/pre-start.erb
- src/scf-release/jobs/sync-integration-tests/templates/pre-start.erb
- src/scf-release/src/acceptance-tests-brain/test-scripts/008_cf_usb_mysql_test.rb
- src/scf-release/src/acceptance-tests-brain/test-scripts/019_cf_usb_postgres_test.rb
Configgin needs to read/write secrets, which is not a capability all pods should have. The `configgin` service account is passed automatically (via fissile) to each container via the `CONFIGGIN_SA_TOKEN` environment variable (from a secret maintained by `configgin-helper`).
`configgin-helper` imports the `MONIT_PASSWORD` from the generated secrets, so will not start until the `secret-generator` is done, so `secret-generator` has to be bound to the `configgin` role too to avoid a deadlock.
Active/passive roles now get their own service account because they need to modify annotations on pods and services (`switchboard-leader`).
`garden-runc` also has a separate service account because it needs to fetch its own pod spec to determine which node it is running on to determine the availability …
> Use separate service account for configgin

- container-host-files/etc/scf/config/role-manifest.yml
The default ciphersuite fails when AWS ELBs are using SSL.
The new default cipher list is similar to the intermediate one recommended by Mozilla, with some changes to preserve compatibility with gorouter defaults, and variant names to work regardless of ELB SSL Policies (it works with all the canned policies).
Ref https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29
Ref https://github.com/SUSE/scf/issues/3153
[jsc#CAP-1125]
> Expand ciphersuite to be compatible with more clients

- container-host-files/etc/scf/config/role-manifest.yml
Also make it configurable via kube.podAntiAffinityTopologyKey.
The original value of beta.kubernetes.io/os doesn't make any sense: it means to try to schedule each pod on a different OS. But our pods only work on Linux, and we don't expect to see any non-Linux nodes in the cluster anyways.
[jsc#CAP-1067]
> Set topologyKey for podAntiAffinity rule to kubernetes.io/hostname

- bin/common/versions.sh
Nothing to see here; this feature is not currently being used by SCF
> Bump fissile to add feature-flag support for colocated containers

- container-host-files/etc/scf/config/role-manifest.yml
This reverts commit f3f1a4a09a02319ad7f709f7a0f9a999ae7a2e47.
Jenkins fails consistently with this error (3 times, because `-flakeAttemtps=3`):
```
[Fail] [detect] Buildpacks php [It] makes the app reachable via its bound route
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/detect/buildpacks.go:98
```
> Revert "Bump sle15 release to 10.74"

- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
apps/v1beta1 is deprecated and will be removed in kube 1.16.
> Use apps/v1 apiVersion for statefulsets

- .gitignore
- Vagrantfile
It doesn't seem to be used at all anymore, and mounting more than one folder in vagrant via NFS seems to be broken in macOS Catalina.
> Remove NFS mount for .fissile/.bosh

- container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
The default service account lacks permission to do so on GKE.
[jsc#CAP-1149]
> Use CONFIGGIN_SA_TOKEN to fetch NATS statefulset

- Jenkinsfile
- bin/common/versions.sh
- container-host-files/etc/scf/config/role-manifest.yml
Remove unnecessary `KUBE_SIZING_*_COUNT` variables
* Remove `KUBE_SIZING_MYSQL_COUNT` environment variable
It is provided by fissile and always corresponds to the number of  mysql instances. This used to be used to set `KUBE_MYSQL_CLUSTER_IPS` in `configure-HA-hosts.sh`. But this logic is only used for `hats` anymore, so there is no reason to restart all `mysql-proxy` pods whenever the `mysql` replica count changes.
* Remove `KUBE_SIZING_NATS_COUNT` for every role except `nats`
This avoids restarting all roles that use the route emitter job any time the number of `nats` instances changes. Only other `nats` pods need to restart to get an up-to-date list of available instances.
* Bump configgin version to 0.20.2
This includes a bug fix to avoid erroneously restarting pods due to incorrectly …
> Fix pod restarts in HA setups

- Jenkinsfile
- bin/common/versions.sh
Use versioned annotation names for the imported property digests, so we start with a blank slate on each chart update.
[jsc#CAP-1148]
> Bump stemcells to get configgin-0.20.3

- .envrc
- .gitmodules
- Makefile
- container-host-files/etc/scf/config/role-manifest.yml
Bump autoscaler to the v1.2.4 release.
Note: This is done via submoduling as v1.2.4 is not available as a final release on bosh.io.
This is a fix for https://jira.suse.com/browse/CAP-630
Vagrant / Jenkins will be run and should work.
> Bump autoscaler to v1.2.4
